SELECT LF.TIPO_LANC_FIN, CF.NOME_CONTA_FINANCEIRA, PC.NOME_PLANO_CONTA, lc.VALOR_PAGO
FROM LANC_FINANCEIRO LF
INNER JOIN CONTA_FINANCEIRA CF ON CF.COD_CONTA_FINANCEIRA = LF.COD_CONTA_FINANCEIRA
INNER JOIN PLANO_CONTA PC ON PC.COD_PLANO_CONTA = LC.COD_PLANO_CONTA
WHERE LF.ATV_LANC_FINANCEIRO = 'V'
AND DATA_PAGAMENTO BETWEEN 'DD.MM.AAAA' AND 'DD.MM.AAAA'