SELECT '-' || CAST(LCF.VALOR_LANCAMENTO_CONTA AS VARCHAR(30)), LCF.DATA_DISPONIVEL
FROM LANC_CONTA_FIN LCF
WHERE LCF.VALOR_SAIDA > 0
AND LCF.COD_CONTA_FINANCEIRA = 25
AND LCF.DATA_DISPONIVEL > '31.12.2024'
AND LCF.REG_ESTORNO IS NULL
AND LCF.LANCAMENTO_ESTORNADO = 'F'
UNION
SELECT LCF.VALOR_LANCAMENTO_CONTA, LCF.DATA_DISPONIVEL
FROM LANC_CONTA_FIN LCF
WHERE LCF.VALOR_ENTRADA > 0
AND LCF.COD_CONTA_FINANCEIRA = 25
AND LCF.DATA_DISPONIVEL > '31.12.2024'
AND LCF.REG_ESTORNO IS NULL
AND LCF.LANCAMENTO_ESTORNADO = 'F'