-- Script gerado automaticamente (DESTINO: PROCEL)
-- Data: 2026-03-22
-- Destino: D:\G3\Dados\PROCEL.FDB
-- Origem de leitura: D:\G3\Dados\DELEAN.FDB


-- ============================================================
-- TABLE: faltando em PROCEL e existentes em BASE_CONFIGURADA
-- ============================================================

-- TABLE: BENEFICIO_FISCAL
CREATE TABLE "BENEFICIO_FISCAL" (
    "COD_BENEFICIO" INTEGER NOT NULL,
    "ID_BENEFICIO" VARCHAR(20) CHARACTER SET "ISO8859_1",
    "NOME_BENEFICIO" VARCHAR(100) CHARACTER SET "ISO8859_1",
    "ICMS_SUBST_TRIB" CHAR(1) DEFAULT 'N' CHARACTER SET "ISO8859_1",
    "TRATA_ICMS_NORMAL" CHAR(1) DEFAULT 'N' CHARACTER SET "ISO8859_1",
    "TRATA_PIS_COFINS" CHAR(1) DEFAULT 'N' CHARACTER SET "ISO8859_1",
    "DESCONTA_BASE_ICMS" CHAR(1) DEFAULT 'N' CHARACTER SET "ISO8859_1",
    "DESCONTA_BASE_ICMS_ST" CHAR(1) DEFAULT 'N' CHARACTER SET "ISO8859_1",
    "DESCONTA_BASE_PIS_COF" CHAR(1) DEFAULT 'N' CHARACTER SET "ISO8859_1",
    PRIMARY KEY ("COD_BENEFICIO")
);

-- TABLE: CTP_E12
CREATE TABLE "CTP_E12" (
    "COD_CTP_E12" INTEGER NOT NULL,
    "NUMEROSERIE" VARCHAR(20) NOT NULL CHARACTER SET "ISO8859_1",
    "MFADICIONAL" VARCHAR(1) CHARACTER SET "ISO8859_1",
    "MODELO" VARCHAR(20) CHARACTER SET "ISO8859_1",
    "NUMERODOUSUARIO" INTEGER,
    "CRZ" INTEGER NOT NULL,
    "COO" INTEGER,
    "CRO" INTEGER,
    "DATAMOVIMENTO" DATE NOT NULL,
    "DATAEMISSAO" DATE,
    "HORAEMISSAO" VARCHAR(6) CHARACTER SET "ISO8859_1",
    "VENDABRUTA" DOUBLE PRECISION,
    "DESCONTOISSQN" DOUBLE PRECISION,
    "CANCELAMENTOISSQN" DOUBLE PRECISION,
    "CANCELAMENTOICMS" DOUBLE PRECISION,
    "ACRECIMOISSQN" DOUBLE PRECISION,
    "ACRECIMOICMS" DOUBLE PRECISION,
    "DESCONTOICMS" DOUBLE PRECISION
);

-- TABLE: CTP_E13
CREATE TABLE "CTP_E13" (
    "COD_CTP_E13" INTEGER NOT NULL,
    "COD_CTP_E12" INTEGER NOT NULL,
    "NUMEROSERIE" VARCHAR(20) NOT NULL CHARACTER SET "ISO8859_1",
    "MFADICIONAL" VARCHAR(1) CHARACTER SET "ISO8859_1",
    "MODELO" VARCHAR(20) CHARACTER SET "ISO8859_1",
    "NUMERODOUSUARIO" INTEGER,
    "CRZ" INTEGER NOT NULL,
    "TOTALIZADORPARCIAL" VARCHAR(7) NOT NULL CHARACTER SET "ISO8859_1",
    "VALORACUMULADO" DOUBLE PRECISION,
    "TIPOTOTALIZADOR" VARCHAR(7) CHARACTER SET "ISO8859_1",
    "POSICAO" INTEGER,
    "ALIQUOTA" DOUBLE PRECISION
);

-- TABLE: CTP_E14
CREATE TABLE "CTP_E14" (
    "COD_CTP_E14" INTEGER NOT NULL,
    "COD_CTP_E12" INTEGER NOT NULL,
    "NUMEROSERIE" VARCHAR(20) NOT NULL CHARACTER SET "ISO8859_1",
    "MFADICIONAL" VARCHAR(1) CHARACTER SET "ISO8859_1",
    "MODELO" VARCHAR(20) CHARACTER SET "ISO8859_1",
    "NUMERODOUSUARIO" INTEGER,
    "CCF_CVC_CBP" INTEGER,
    "COO" INTEGER NOT NULL,
    "DATA_INICIO" DATE NOT NULL,
    "SUBTOTAL" DOUBLE PRECISION,
    "DESCONTO" DOUBLE PRECISION,
    "TIPO_DESCONTO" VARCHAR(1) CHARACTER SET "ISO8859_1",
    "ACRESCIMO" DOUBLE PRECISION,
    "TIPO_ACRESCIMO" VARCHAR(1) CHARACTER SET "ISO8859_1",
    "TOTAL_LIQUIDO" DOUBLE PRECISION,
    "CANCELADO" VARCHAR(1) CHARACTER SET "ISO8859_1",
    "VALOR_CANCELADO" DOUBLE PRECISION,
    "ORDEM_DESC_ACRES" VARCHAR(1) CHARACTER SET "ISO8859_1",
    "NOME_CLIENTE" VARCHAR(40) CHARACTER SET "ISO8859_1",
    "CPF_CNPJ" VARCHAR(14) CHARACTER SET "ISO8859_1"
);

-- TABLE: CTP_E15
CREATE TABLE "CTP_E15" (
    "COD_CTP_E15" INTEGER NOT NULL,
    "COD_CTP_E14" INTEGER NOT NULL,
    "COD_CTP_E13" INTEGER NOT NULL,
    "COD_CTP_E12" INTEGER NOT NULL,
    "NUMEROSERIE" VARCHAR(20) NOT NULL CHARACTER SET "ISO8859_1",
    "MFADICIONAL" VARCHAR(1) CHARACTER SET "ISO8859_1",
    "MODELO" VARCHAR(20) CHARACTER SET "ISO8859_1",
    "NUMERODOUSUARIO" INTEGER,
    "COO" INTEGER NOT NULL,
    "CCF_CVC_CBP" INTEGER,
    "NUMITEM" INTEGER NOT NULL,
    "CODIGO_PRODUTO" VARCHAR(14) CHARACTER SET "ISO8859_1",
    "DESCRICAO" VARCHAR(100) CHARACTER SET "ISO8859_1",
    "QUANTIDADE" DOUBLE PRECISION,
    "UNIDADE" VARCHAR(3) CHARACTER SET "ISO8859_1",
    "VALOR_UNITARIO" DOUBLE PRECISION,
    "DESCONTO_ITEM" DOUBLE PRECISION,
    "ACRESCIMO_ITEM" DOUBLE PRECISION,
    "TOTAL_LIQUIDO" DOUBLE PRECISION,
    "TOTALIZADOR" VARCHAR(7) NOT NULL CHARACTER SET "ISO8859_1",
    "CANCELADO" VARCHAR(1) CHARACTER SET "ISO8859_1",
    "QUANTIDADE_CANCELADA" DOUBLE PRECISION,
    "VALOR_CANCELADO" DOUBLE PRECISION,
    "VALOR_CANC_ACRESCIMO" DOUBLE PRECISION,
    "ARRED_TRUNC" VARCHAR(1) CHARACTER SET "ISO8859_1",
    "CASAS_QUANTIDADE" INTEGER,
    "CASAS_VALOR" INTEGER,
    "CST" VARCHAR(3) CHARACTER SET "ISO8859_1",
    "CODPROD" VARCHAR(5) CHARACTER SET "ISO8859_1",
    "ICMS" DOUBLE PRECISION,
    "CFOP" VARCHAR(10) CHARACTER SET "ISO8859_1",
    "CODIGO_PRODUTO_INT" INTEGER
);

-- TABLE: ECF_REDUCAO_ADD
CREATE TABLE "ECF_REDUCAO_ADD" (
    "COD_ECF_REDUCAO_ADD" INTEGER NOT NULL,
    "DTC_ECF_REDUCAO_ADD" TIMESTAMP,
    "CRZ" INTEGER,
    "COD_ECF" INTEGER,
    "COO_INICIAL" INTEGER
);

-- TABLE: ECF_REDUCAO_ANALITICO
CREATE TABLE "ECF_REDUCAO_ANALITICO" (
    "COD_ECF_REDUCAO_ANALITICO" INTEGER NOT NULL,
    "COD_ECF_REDUCAO" INTEGER,
    "COD_ECF" INTEGER,
    "DATA_MOVIMENTO" DATE,
    "CST" VARCHAR(5) CHARACTER SET "ISO8859_1",
    "CFOP" VARCHAR(5) CHARACTER SET "ISO8859_1",
    "ICMS" DOUBLE PRECISION,
    "VALOR" DOUBLE PRECISION,
    "BASE_ICMS" DOUBLE PRECISION,
    "VALOR_ICMS" DOUBLE PRECISION,
    "BASE_ICMS_ST" DOUBLE PRECISION,
    "VALOR_ICMS_ST" DOUBLE PRECISION,
    "REDUCAO_BASE" DOUBLE PRECISION,
    "VALOR_IPI" DOUBLE PRECISION,
    "INTEGRACAO" INTEGER
);

-- TABLE: ECF_REDUCAO_CUPOM
CREATE TABLE "ECF_REDUCAO_CUPOM" (
    "COD_ECF_REDUCAO_CUPOM" INTEGER NOT NULL,
    "COD_ECF_REDUCAO" INTEGER,
    "COD_ECF" INTEGER,
    "COD_MOD" VARCHAR(2) CHARACTER SET "ISO8859_1",
    "COD_SIT" VARCHAR(2) CHARACTER SET "ISO8859_1",
    "COO" VARCHAR(10) CHARACTER SET "ISO8859_1",
    "DT_DOC" DATE NOT NULL,
    "VL_DOC" DOUBLE PRECISION,
    "VL_PIS" DOUBLE PRECISION,
    "VL_COFINS" DOUBLE PRECISION,
    "CPF_CNPJ" VARCHAR(14) CHARACTER SET "ISO8859_1",
    "NOM_ADQ" VARCHAR(60) CHARACTER SET "ISO8859_1"
);

-- TABLE: ECF_REDUCAO_CUPOM_ITEM
CREATE TABLE "ECF_REDUCAO_CUPOM_ITEM" (
    "COD_ECF_REDUCAO_CUPOM_ITEM" INTEGER NOT NULL,
    "COD_ECF_REDUCAO_CUPOM" INTEGER,
    "TOTALIZADOR_PARCIAL" VARCHAR(10) CHARACTER SET "ISO8859_1",
    "COD_MATERIAL" INTEGER NOT NULL,
    "QTD" DOUBLE PRECISION,
    "QTD_CANC" DOUBLE PRECISION,
    "UNID" VARCHAR(20) CHARACTER SET "ISO8859_1",
    "VL_ITEM" DOUBLE PRECISION,
    "CST_ICMS" VARCHAR(3) CHARACTER SET "ISO8859_1",
    "CFOP" VARCHAR(4) CHARACTER SET "ISO8859_1",
    "ALIQ_ICMS" DOUBLE PRECISION,
    "VL_PIS" DOUBLE PRECISION,
    "VL_COFINS" DOUBLE PRECISION,
    "CANCELADO" VARCHAR(1) CHARACTER SET "ISO8859_1"
);

-- TABLE: ECF_REDUCAO_PRODUTO
CREATE TABLE "ECF_REDUCAO_PRODUTO" (
    "COD_ECF_REDUCAO_PRODUTO" INTEGER NOT NULL,
    "COD_ECF_REDUCAO_DETALHE" INTEGER,
    "COO" VARCHAR(10) CHARACTER SET "ISO8859_1",
    "COD_ECF" INTEGER,
    "COD_MATERIAL" INTEGER NOT NULL,
    "TOTALIZADOR_PARCIAL" VARCHAR(10) CHARACTER SET "ISO8859_1",
    "QUANTIDADE" DOUBLE PRECISION,
    "UNIDADE" VARCHAR(20) CHARACTER SET "ISO8859_1",
    "VALOR_ITEM" DOUBLE PRECISION,
    "VALOR_PIS" DOUBLE PRECISION,
    "VALOR_COFINS" DOUBLE PRECISION,
    "VALOR_ITEM_CANC" DOUBLE PRECISION,
    "VALOR_NORMAL" DOUBLE PRECISION,
    "VALOR_DESCONTO" DOUBLE PRECISION,
    "VALOR_ACRESCIMO" DOUBLE PRECISION,
    "COD_ECF_REDUCAO_PRODUTO_CHK" INTEGER
);

-- TABLE: FRENTE_CAIXA_STATUS
CREATE TABLE "FRENTE_CAIXA_STATUS" (
    "COD_FRENTE_CAIXA" INTEGER NOT NULL,
    "CHECKWIN_INTEG_NULL" INTEGER,
    "CHECKWIN_INTEG_0" INTEGER,
    "CHECKWIN_INTEG_1" INTEGER,
    "CHECKWIN_INTEG_2" INTEGER,
    "CHECKWIN_DATA_ATU" TIMESTAMP
);

-- TABLE: LOG_AJUSTE_C460
CREATE TABLE "LOG_AJUSTE_C460" (
    "PK" INTEGER,
    "ID" INTEGER,
    "DIF" DOUBLE PRECISION,
    "DTC" TIMESTAMP DEFAULT 'NOW'
);

-- TABLE: MONITOR_QUERIES
CREATE TABLE "MONITOR_QUERIES" (
    "QUERY_ID" INTEGER NOT NULL,
    "CATEGORY_ID" INTEGER NOT NULL,
    "QUERY_CAPTION" BLOB,
    "QUERY_TEXT" BLOB,
    "QUERY_TEXT1" BLOB,
    PRIMARY KEY ("QUERY_ID")
);

-- TABLE: NATUREZA_OPER_BENEF_FISCAL
CREATE TABLE "NATUREZA_OPER_BENEF_FISCAL" (
    "COD_NATUREZA_OPER" INTEGER NOT NULL,
    "COD_BENEFICIO" INTEGER NOT NULL,
    PRIMARY KEY ("COD_NATUREZA_OPER", "COD_BENEFICIO")
);

-- TABLE: PARAMETRO_CHK
CREATE TABLE "PARAMETRO_CHK" (
    "COD_PARAMETRO_CHK" INTEGER NOT NULL,
    "NOME" VARCHAR(100) NOT NULL CHARACTER SET "ISO8859_1",
    "VALOR" VARCHAR(255) CHARACTER SET "ISO8859_1",
    "VALOR_DEFAULT" VARCHAR(255) CHARACTER SET "ISO8859_1",
    "DTC_PARAMETRO_CHK" TIMESTAMP DEFAULT 'NOW',
    "VALIDADO" INTEGER DEFAULT 0,
    "INTEGRACAO" INTEGER DEFAULT 0
);

-- TABLE: PARAMETRO_CHK_FRENTECAIXA
CREATE TABLE "PARAMETRO_CHK_FRENTECAIXA" (
    "COD_PARAMETRO_CHK_FRENTECAIXA" INTEGER NOT NULL,
    "COD_PARAMETRO_CHK" INTEGER,
    "COD_FRENTE_CAIXA" INTEGER NOT NULL,
    "VALOR" VARCHAR(255) CHARACTER SET "ISO8859_1",
    "VALIDADO" INTEGER DEFAULT 0,
    "INTEGRACAO" INTEGER DEFAULT 0
);

-- TABLE: RES_ECF
CREATE TABLE "RES_ECF" (
    "COD_RES_ECF" INTEGER NOT NULL,
    "COD_EMPRESA_FIN" INTEGER,
    "DATA" DATE,
    "NUMEROECF" INTEGER,
    "COO_INICIO" INTEGER,
    "COO_FINAL" INTEGER,
    "GT_INICIAL" DOUBLE PRECISION,
    "GT_FINAL" DOUBLE PRECISION,
    "CANCELAMENTOS" DOUBLE PRECISION,
    "DESCONTOS" DOUBLE PRECISION,
    "VALORCONTABIL" DOUBLE PRECISION,
    "ISENTONAOTRIB" DOUBLE PRECISION,
    "DEBITOIMPOSTO" DOUBLE PRECISION,
    "CONTADORREDUCOES" DOUBLE PRECISION,
    "SERIALECF" VARCHAR(20) CHARACTER SET "ISO8859_1",
    "DTC_RES_ECF" TIMESTAMP,
    "ATV_RES_ECF" CHAR(1) CHARACTER SET "ISO8859_1",
    "REINICIO" INTEGER,
    "CRZ" INTEGER,
    "CRO" INTEGER,
    "VALOR_RENDA_BRUTA" NUMERIC(15,4),
    "VALOR_TOTALIZADOR_GERAL" NUMERIC(15,4),
    "REGISTRO_COMPLETO" VARCHAR(250) CHARACTER SET "ISO8859_1"
);

-- TABLE: RES_ECFA
CREATE TABLE "RES_ECFA" (
    "COD_RES_ECFA" INTEGER NOT NULL,
    "COD_RES_ECF" INTEGER,
    "ALIQ" DOUBLE PRECISION,
    "VALORVENDIDO" DOUBLE PRECISION,
    "VALORIMPOSTO" DOUBLE PRECISION,
    "REGISTRO_COMPLETO" VARCHAR(250) CHARACTER SET "ISO8859_1"
);

-- TABLE: SINTEGRA_REGISTRO
CREATE TABLE "SINTEGRA_REGISTRO" (
    "COD_SINTEGRA_REGISTRO" INTEGER NOT NULL,
    "REGISTRO" VARCHAR(4) CHARACTER SET "ISO8859_1",
    "OCORRENCIA" INTEGER,
    "OBRIGATORIO" VARCHAR(1) CHARACTER SET "ISO8859_1",
    "SQL" BLOB SUB_TYPE TEXT,
    "TIPO_SQL" VARCHAR(1) CHARACTER SET "ISO8859_1",
    "ORDEM" INTEGER
);

-- TABLE: SINTEGRA_REGISTRO_ITEM
CREATE TABLE "SINTEGRA_REGISTRO_ITEM" (
    "COD_SINTEGRA_REGISTRO_ITEM" INTEGER NOT NULL,
    "COD_SINTEGRA_REGISTRO" INTEGER,
    "CAMPO" VARCHAR(50) CHARACTER SET "ISO8859_1",
    "OBRIGATORIO" VARCHAR(1) CHARACTER SET "ISO8859_1",
    "ORDEM" INTEGER
);

-- TABLE: SINTEGRA_REGISTRO_VALOR
CREATE TABLE "SINTEGRA_REGISTRO_VALOR" (
    "COD_SINTEGRA_REGISTRO_VALOR" INTEGER NOT NULL,
    "COD_SINTEGRA_REGISTRO_ITEM" INTEGER,
    "ITEM" INTEGER,
    "ITEM_FILHO" INTEGER,
    "VALOR" VARCHAR(255) CHARACTER SET "ISO8859_1"
);

-- TABLE: SINTEGRA_TMP__10
CREATE TABLE "SINTEGRA_TMP__10" (
    "PK" INTEGER NOT NULL,
    "FK" INTEGER,
    "CGC_MF" VARCHAR(20) CHARACTER SET "ISO8859_1",
    "INSC_EST" VARCHAR(20) CHARACTER SET "ISO8859_1",
    "NOME_CONTRIBUINTE" VARCHAR(100) CHARACTER SET "ISO8859_1",
    "MUNICIPIO" VARCHAR(100) CHARACTER SET "ISO8859_1",
    "UF" VARCHAR(10) CHARACTER SET "ISO8859_1",
    "FAX" VARCHAR(100) CHARACTER SET "ISO8859_1",
    "DATA_INICIAL" VARCHAR(10) CHARACTER SET "ISO8859_1",
    "DATA_FINAL" VARCHAR(10) CHARACTER SET "ISO8859_1",
    "COD_CONVENIO" VARCHAR(1) CHARACTER SET "ISO8859_1",
    "COD_OPERACAO" VARCHAR(1) CHARACTER SET "ISO8859_1",
    "COD_FINALIDADE" VARCHAR(1) CHARACTER SET "ISO8859_1",
    PRIMARY KEY ("PK")
);

-- TABLE: SINTEGRA_TMP__11
CREATE TABLE "SINTEGRA_TMP__11" (
    "PK" INTEGER NOT NULL,
    "FK" INTEGER,
    "LOGRADOURO" VARCHAR(100) CHARACTER SET "ISO8859_1",
    "NRO" VARCHAR(20) CHARACTER SET "ISO8859_1",
    "COMPLEMENTO" VARCHAR(40) CHARACTER SET "ISO8859_1",
    "BAIRRO" VARCHAR(50) CHARACTER SET "ISO8859_1",
    "CEP" VARCHAR(10) CHARACTER SET "ISO8859_1",
    "NOME_CONTATO" VARCHAR(50) CHARACTER SET "ISO8859_1",
    "TELEFONE" VARCHAR(100) CHARACTER SET "ISO8859_1",
    PRIMARY KEY ("PK")
);

-- TABLE: SPEDCTMP_A010
CREATE TABLE "SPEDCTMP_A010" (
    "PK" INTEGER NOT NULL,
    "FK" INTEGER,
    "CNPJ" VARCHAR(255) CHARACTER SET "ISO8859_1",
    PRIMARY KEY ("PK")
);

-- TABLE: SPEDCTMP_A100
CREATE TABLE "SPEDCTMP_A100" (
    "PK" INTEGER NOT NULL,
    "FK" INTEGER,
    "ID" INTEGER,
    "IND_OPER" INTEGER,
    "IND_EMIT" INTEGER,
    "COD_PART" INTEGER,
    "COD_SIT" VARCHAR(2) CHARACTER SET "ISO8859_1",
    "SER" VARCHAR(10) CHARACTER SET "ISO8859_1",
    "SUB" VARCHAR(255) CHARACTER SET "ISO8859_1",
    "NUM_DOC" INTEGER,
    "CHV_NFSE" VARCHAR(255) CHARACTER SET "ISO8859_1",
    "DT_DOC" TIMESTAMP,
    "DT_EXE_SERV" TIMESTAMP,
    "VL_DOC" DOUBLE PRECISION,
    "IND_PGTO" INTEGER,
    "VL_DESC" DOUBLE PRECISION,
    "VL_BC_PIS" DOUBLE PRECISION,
    "VL_PIS" NUMERIC(15,2),
    "VL_BC_COFINS" DOUBLE PRECISION,
    "VL_COFINS" NUMERIC(15,2),
    "VL_PIS_RET" DOUBLE PRECISION,
    "VL_COFINS_RET" DOUBLE PRECISION,
    "VL_ISS" DOUBLE PRECISION,
    PRIMARY KEY ("PK")
);

-- TABLE: SPEDCTMP_A170
CREATE TABLE "SPEDCTMP_A170" (
    "PK" INTEGER NOT NULL,
    "FK" INTEGER,
    "ID" INTEGER,
    "NUM_ITEM" INTEGER,
    "COD_ITEM" BIGINT,
    "DESCR_COMPL" VARCHAR(2000) CHARACTER SET "ISO8859_1",
    "VL_ITEM" DOUBLE PRECISION,
    "VL_DESC" DOUBLE PRECISION,
    "NAT_BC_CRED" VARCHAR(255) CHARACTER SET "ISO8859_1",
    "IND_ORIG_CRED" VARCHAR(255) CHARACTER SET "ISO8859_1",
    "CST_PIS" VARCHAR(2) CHARACTER SET "ISO8859_1",
    "VL_BC_PIS" DOUBLE PRECISION,
    "ALIQ_PIS" DOUBLE PRECISION,
    "VL_PIS" DOUBLE PRECISION,
    "CST_COFINS" VARCHAR(2) CHARACTER SET "ISO8859_1",
    "VL_BC_COFINS" DOUBLE PRECISION,
    "ALIQ_COFINS" DOUBLE PRECISION,
    "VL_COFINS" DOUBLE PRECISION,
    "COD_CTA" VARCHAR(100) CHARACTER SET "ISO8859_1",
    "COD_CCUS" VARCHAR(100) CHARACTER SET "ISO8859_1",
    PRIMARY KEY ("PK")
);

-- TABLE: SPEDCTMP_C010
CREATE TABLE "SPEDCTMP_C010" (
    "PK" INTEGER NOT NULL,
    "FK" INTEGER,
    "CNPJ" VARCHAR(255) CHARACTER SET "ISO8859_1",
    "IND_ESCRI" VARCHAR(1) CHARACTER SET "ISO8859_1",
    PRIMARY KEY ("PK")
);

-- TABLE: SPEDCTMP_C100
CREATE TABLE "SPEDCTMP_C100" (
    "PK" INTEGER NOT NULL,
    "FK" INTEGER,
    "ID" BIGINT,
    "NOMEREL" VARCHAR(100) CHARACTER SET "ISO8859_1",
    "COD_CTA" VARCHAR(50) CHARACTER SET "ISO8859_1",
    "COD_CTAD" VARCHAR(30) CHARACTER SET "ISO8859_1",
    "COD_CTAC" VARCHAR(30) CHARACTER SET "ISO8859_1",
    "IND_OPER" INTEGER,
    "IND_EMIT" INTEGER,
    "COD_PART" INTEGER,
    "COD_MOD" VARCHAR(10) CHARACTER SET "ISO8859_1",
    "NFCE_SERIE" INTEGER,
    "COD_SIT" VARCHAR(2) CHARACTER SET "ISO8859_1",
    "SER" VARCHAR(44) CHARACTER SET "ISO8859_1",
    "NUM_DOC" VARCHAR(20) CHARACTER SET "ISO8859_1",
    "CHV_NFE" VARCHAR(44) CHARACTER SET "ISO8859_1",
    "DT_DOC" TIMESTAMP,
    "DT_E_S" TIMESTAMP,
    "VL_DOC" DOUBLE PRECISION,
    "IND_PGTO" INTEGER,
    "UF" VARCHAR(10) CHARACTER SET "ISO8859_1",
    "UF_DESTINATARIO" VARCHAR(10) CHARACTER SET "ISO8859_1",
    "VL_DESC" DOUBLE PRECISION,
    "VL_ABAT_NT" DOUBLE PRECISION,
    "VL_MERC" DOUBLE PRECISION,
    "IND_FRT" INTEGER,
    "VL_FRT" DOUBLE PRECISION,
    "VL_SEG" DOUBLE PRECISION,
    "VL_OUT_DA" DOUBLE PRECISION,
    "VL_BC_ICMS" DOUBLE PRECISION,
    "VL_ICMS" DOUBLE PRECISION,
    "VL_BC_ICMS_ST" DOUBLE PRECISION,
    "VL_ICMS_ST" DOUBLE PRECISION,
    "VL_PIS" DOUBLE PRECISION,
    "VL_COFINS" DOUBLE PRECISION,
    "VL_PIS_ST" BIGINT,
    "VL_COFINS_ST" BIGINT,
    "VL_IPI" DOUBLE PRECISION,
    "MAX_NUM_ITEM" INTEGER,
    PRIMARY KEY ("PK")
);

-- TABLE: SPEDCTMP_C110
CREATE TABLE "SPEDCTMP_C110" (
    "PK" INTEGER NOT NULL,
    "FK" INTEGER,
    "ID" BIGINT,
    "COD_INF" VARCHAR(6) CHARACTER SET "ISO8859_1",
    "DESCRICAO_INF" VARCHAR(65) CHARACTER SET "ISO8859_1",
    "TXT_COMPL" VARCHAR(250) CHARACTER SET "ISO8859_1",
    "TIPOCABECALHO" VARCHAR(4) CHARACTER SET "ISO8859_1",
    PRIMARY KEY ("PK")
);

-- TABLE: SPEDCTMP_C120
CREATE TABLE "SPEDCTMP_C120" (
    "PK" INTEGER NOT NULL,
    "FK" INTEGER,
    "COD_DOC_IMP" INTEGER,
    "NUM_DOC_IMP" VARCHAR(10) CHARACTER SET "ISO8859_1",
    "VL_PIS_IMP" VARCHAR(1) CHARACTER SET "ISO8859_1",
    "VL_COFINS_IMP" VARCHAR(1) CHARACTER SET "ISO8859_1",
    "NUM_ACDRAW" VARCHAR(1) CHARACTER SET "ISO8859_1",
    PRIMARY KEY ("PK")
);

-- TABLE: SPEDCTMP_C170
CREATE TABLE "SPEDCTMP_C170" (
    "PK" INTEGER NOT NULL,
    "FK" INTEGER,
    "ID" BIGINT,
    "NUM_ITEM" INTEGER,
    "COD_ITEM" BIGINT,
    "DESCR_COMPL" VARCHAR(255) CHARACTER SET "ISO8859_1",
    "QTD" NUMERIC(15,5),
    "UNID" INTEGER,
    "UNID_STR" VARCHAR(20) CHARACTER SET "ISO8859_1",
    "VL_ITEM" DOUBLE PRECISION,
    "VL_DESC" DOUBLE PRECISION,
    "IND_MOV" INTEGER,
    "CST_ICMS" VARCHAR(6) CHARACTER SET "ISO8859_1",
    "CFOP" VARCHAR(255) CHARACTER SET "ISO8859_1",
    "COD_NAT" INTEGER,
    "VL_BC_ICMS" NUMERIC(15,2),
    "ALIQ_ICMS" DOUBLE PRECISION,
    "VL_ICMS" DOUBLE PRECISION,
    "VL_BC_ICMS_ST" DOUBLE PRECISION,
    "ALIQ_ST" NUMERIC(15,2),
    "VL_ICMS_ST" DOUBLE PRECISION,
    "IND_APUR" INTEGER,
    "CST_IPI" VARCHAR(11) CHARACTER SET "ISO8859_1",
    "COD_ENQ" VARCHAR(255) CHARACTER SET "ISO8859_1",
    "VL_BC_IPI" NUMERIC(15,2),
    "ALIQ_IPI" DOUBLE PRECISION,
    "VL_IPI" DOUBLE PRECISION,
    "CST_PIS" VARCHAR(2) CHARACTER SET "ISO8859_1",
    "VL_BC_PIS" DOUBLE PRECISION,
    "ALIQ_PIS" DOUBLE PRECISION,
    "QUANT_BC_PIS" NUMERIC(15,3),
    "ALIQ_PIS_REAIS" DOUBLE PRECISION,
    "VL_PIS" NUMERIC(15,2),
    "CST_COFINS" VARCHAR(2) CHARACTER SET "ISO8859_1",
    "VL_BC_COFINS" DOUBLE PRECISION,
    "ALIQ_COFINS" DOUBLE PRECISION,
    "QUANT_BC_COFINS" NUMERIC(15,3),
    "ALIQ_COFINS_REAIS" DOUBLE PRECISION,
    "VL_COFINS" NUMERIC(15,2),
    "COD_CTA" VARCHAR(20) CHARACTER SET "ISO8859_1",
    "ORIGEM" VARCHAR(3) CHARACTER SET "ISO8859_1",
    "APRESENTARC170" INTEGER,
    "VL_OUT_DA" DOUBLE PRECISION,
    "VL_OPR" NUMERIC(15,2),
    "VL_ABAT_NT" INTEGER,
    PRIMARY KEY ("PK")
);

-- TABLE: SPEDCTMP_C400
CREATE TABLE "SPEDCTMP_C400" (
    "PK" INTEGER NOT NULL,
    "FK" INTEGER,
    "ID" INTEGER,
    "COD_MOD" VARCHAR(2) CHARACTER SET "ISO8859_1",
    "ECF_MOD" VARCHAR(20) CHARACTER SET "ISO8859_1",
    "ECF_FAB" VARCHAR(50) CHARACTER SET "ISO8859_1",
    "ECF_CX" VARCHAR(5) CHARACTER SET "ISO8859_1",
    "COD_ECF" INTEGER,
    PRIMARY KEY ("PK")
);

-- TABLE: SPEDCTMP_C405
CREATE TABLE "SPEDCTMP_C405" (
    "PK" INTEGER NOT NULL,
    "FK" INTEGER,
    "COD_ECF" INTEGER,
    "ID" INTEGER,
    "DT_DOC" DATE,
    "CRO" INTEGER,
    "CRZ" INTEGER,
    "NUM_COO_FIN" INTEGER,
    "GT_FIN" NUMERIC(15,2),
    "VL_BRT" NUMERIC(15,2),
    "NUM_COO_INI" BIGINT,
    PRIMARY KEY ("PK")
);

-- TABLE: SPEDCTMP_D100
CREATE TABLE "SPEDCTMP_D100" (
    "PK" INTEGER NOT NULL,
    "FK" INTEGER,
    "COD_NF_EXTRA" INTEGER,
    "IND_OPER" INTEGER,
    "IND_EMIT" INTEGER,
    "COD_PART" INTEGER,
    "COD_MOD" VARCHAR(10) CHARACTER SET "ISO8859_1",
    "COD_SIT" VARCHAR(2) CHARACTER SET "ISO8859_1",
    "SER" VARCHAR(5) CHARACTER SET "ISO8859_1",
    "SUB" VARCHAR(2) CHARACTER SET "ISO8859_1",
    "NUM_DOC_D100" INTEGER,
    "CHV_CTE" VARCHAR(50) CHARACTER SET "ISO8859_1",
    "DT_DOC" TIMESTAMP,
    "DT_A_P" TIMESTAMP,
    "TP_CTE" VARCHAR(1) CHARACTER SET "ISO8859_1",
    "CHV_CTE_REF" VARCHAR(255) CHARACTER SET "ISO8859_1",
    "VL_DOC" DOUBLE PRECISION,
    "VL_DESC" DOUBLE PRECISION,
    "IND_FRT" VARCHAR(1) CHARACTER SET "ISO8859_1",
    "VL_SERV" DOUBLE PRECISION,
    "VL_BC_ICMS" DOUBLE PRECISION,
    "VL_ICMS" DOUBLE PRECISION,
    "VL_NT" DOUBLE PRECISION,
    "COD_INF" VARCHAR(255) CHARACTER SET "ISO8859_1",
    "COD_CTA" VARCHAR(255) CHARACTER SET "ISO8859_1",
    "UF" VARCHAR(10) CHARACTER SET "ISO8859_1",
    "CST_ICMS" VARCHAR(3) CHARACTER SET "ISO8859_1",
    "CFOP" VARCHAR(10) CHARACTER SET "ISO8859_1",
    "ALIQ_ICMS" DOUBLE PRECISION,
    "COD_MUN_ORIG" VARCHAR(12) CHARACTER SET "ISO8859_1",
    "COD_MUN_DEST" VARCHAR(12) CHARACTER SET "ISO8859_1",
    PRIMARY KEY ("PK")
);

-- TABLE: SPEDCTMP_D500
CREATE TABLE "SPEDCTMP_D500" (
    "PK" INTEGER NOT NULL,
    "FK" INTEGER,
    "ID" BIGINT,
    "IND_OPER" INTEGER,
    "IND_EMIT" INTEGER,
    "COD_PART" INTEGER,
    "COD_MOD" VARCHAR(10) CHARACTER SET "ISO8859_1",
    "COD_SIT" VARCHAR(2) CHARACTER SET "ISO8859_1",
    "SER" VARCHAR(20) CHARACTER SET "ISO8859_1",
    "SUB" VARCHAR(255) CHARACTER SET "ISO8859_1",
    "NUM_DOC" VARCHAR(20) CHARACTER SET "ISO8859_1",
    "DT_DOC" TIMESTAMP,
    "DT_A_P" TIMESTAMP,
    "VL_DOC" DOUBLE PRECISION,
    "VL_DESC" DOUBLE PRECISION,
    "VL_SERV" DOUBLE PRECISION,
    "VL_SERV_NT" DOUBLE PRECISION,
    "VL_TERC" DOUBLE PRECISION,
    "VL_DA" DOUBLE PRECISION,
    "VL_BC_ICMS" DOUBLE PRECISION,
    "VL_ICMS" DOUBLE PRECISION,
    "COD_INF" VARCHAR(255) CHARACTER SET "ISO8859_1",
    "VL_PIS" NUMERIC(15,2),
    "VL_COFINS" NUMERIC(15,2),
    "COD_CTA" VARCHAR(255) CHARACTER SET "ISO8859_1",
    "TP_ASSINANTE" VARCHAR(5) CHARACTER SET "ISO8859_1",
    PRIMARY KEY ("PK")
);

-- TABLE: SPEDCTMP_M610
CREATE TABLE "SPEDCTMP_M610" (
    "PK" INTEGER NOT NULL,
    "FK" INTEGER,
    "COD_CONT" VARCHAR(2) CHARACTER SET "ISO8859_1",
    "VL_REC_BRT" NUMERIC(15,2),
    "VL_BC_CONT" NUMERIC(15,2),
    "VL_AJUS_ACRES_BC_COFINS" DOUBLE PRECISION,
    "VL_AJUS_REDUC_BC_COFINS" DOUBLE PRECISION,
    "VL_BC_CONT_AJUS" NUMERIC(15,2),
    "ALIQ_COFINS" DOUBLE PRECISION,
    "QUANT_BC_COFINS" DOUBLE PRECISION,
    "ALIQ_COFINS_QUANT" VARCHAR(255) CHARACTER SET "ISO8859_1",
    "VL_CONT_APUR" NUMERIC(15,2),
    "VL_AJUS_ACRES" DOUBLE PRECISION,
    "VL_AJUS_REDUC" DOUBLE PRECISION,
    "VL_CONT_DIFER" DOUBLE PRECISION,
    "VL_CONT_DIFER_ANT" DOUBLE PRECISION,
    "VL_CONT_PER" NUMERIC(15,2),
    PRIMARY KEY ("PK")
);

-- TABLE: SPEDTMP_1400
CREATE TABLE "SPEDTMP_1400" (
    "PK" INTEGER NOT NULL,
    "FK" INTEGER,
    "COD_ITEM" INTEGER,
    "MUN" VARCHAR(12) CHARACTER SET "ISO8859_1",
    "VALOR" DOUBLE PRECISION,
    PRIMARY KEY ("PK")
);

-- TABLE: SPEDTMP_1600
CREATE TABLE "SPEDTMP_1600" (
    "PK" INTEGER NOT NULL,
    "FK" INTEGER,
    "COD_PART" INTEGER,
    "TOT_CREDITO" DOUBLE PRECISION,
    "TOT_DEBITO" DOUBLE PRECISION,
    PRIMARY KEY ("PK")
);

-- TABLE: SPEDTMP_1601
CREATE TABLE "SPEDTMP_1601" (
    "PK" INTEGER NOT NULL,
    "FK" INTEGER,
    "COD_PART_IP" INTEGER,
    "COD_PART_IT" INTEGER,
    "TOT_VS" DOUBLE PRECISION,
    "TOT_ISS" NUMERIC(15,2),
    "TOT_OUTROS" NUMERIC(15,2),
    PRIMARY KEY ("PK")
);

-- TABLE: SPEDTMP_C101
CREATE TABLE "SPEDTMP_C101" (
    "PK" INTEGER NOT NULL,
    "FK" INTEGER,
    "VL_FCP_UF_DEST" DOUBLE PRECISION,
    "VL_ICMS_UF_DES" DOUBLE PRECISION,
    "VL_ICMS_UF_REM" DOUBLE PRECISION,
    "UF" VARCHAR(2) CHARACTER SET "ISO8859_1",
    PRIMARY KEY ("PK")
);

-- TABLE: SPEDTMP_C113
CREATE TABLE "SPEDTMP_C113" (
    "PK" INTEGER NOT NULL,
    "FK" INTEGER,
    "IND_OPER" VARCHAR(1) CHARACTER SET "ISO8859_1",
    "IND_EMIT" VARCHAR(11) CHARACTER SET "ISO8859_1",
    "COD_PART" INTEGER,
    "COD_MOD" VARCHAR(10) CHARACTER SET "ISO8859_1",
    "SER" VARCHAR(44) CHARACTER SET "ISO8859_1",
    "SUB" VARCHAR(255) CHARACTER SET "ISO8859_1",
    "NUM_DOC" VARCHAR(20) CHARACTER SET "ISO8859_1",
    "DT_DOC" TIMESTAMP,
    "COD_VENDA" INTEGER,
    "CHV_DOCE" VARCHAR(44) CHARACTER SET "ISO8859_1",
    PRIMARY KEY ("PK")
);

-- TABLE: SPEDTMP_C114
CREATE TABLE "SPEDTMP_C114" (
    "PK" INTEGER NOT NULL,
    "FK" INTEGER,
    "COD_MOD" VARCHAR(2) CHARACTER SET "ISO8859_1",
    "ECF_FAB" VARCHAR(50) CHARACTER SET "ISO8859_1",
    "ECF_CX" VARCHAR(3) CHARACTER SET "ISO8859_1",
    "NUM_DOC" VARCHAR(20) CHARACTER SET "ISO8859_1",
    "DT_DOC" TIMESTAMP,
    PRIMARY KEY ("PK")
);

-- TABLE: SPEDTMP_C500
CREATE TABLE "SPEDTMP_C500" (
    "PK" INTEGER NOT NULL,
    "FK" INTEGER,
    "ID" BIGINT,
    "IND_OPER" INTEGER,
    "IND_EMIT" INTEGER,
    "COD_PART" INTEGER,
    "COD_MOD" VARCHAR(10) CHARACTER SET "ISO8859_1",
    "COD_SIT" VARCHAR(2) CHARACTER SET "ISO8859_1",
    "SER" VARCHAR(20) CHARACTER SET "ISO8859_1",
    "SUB" VARCHAR(255) CHARACTER SET "ISO8859_1",
    "COD_CONS" VARCHAR(5) CHARACTER SET "ISO8859_1",
    "NUM_DOC" VARCHAR(20) CHARACTER SET "ISO8859_1",
    "DT_DOC" TIMESTAMP,
    "DT_E_S" TIMESTAMP,
    "VL_DOC" DOUBLE PRECISION,
    "VL_DESC" DOUBLE PRECISION,
    "VL_FORN" DOUBLE PRECISION,
    "VL_SERV_NT" DOUBLE PRECISION,
    "VL_TERC" DOUBLE PRECISION,
    "VL_DA" DOUBLE PRECISION,
    "VL_BC_ICMS" DOUBLE PRECISION,
    "VL_ICMS" DOUBLE PRECISION,
    "VL_BC_ICMS_ST" DOUBLE PRECISION,
    "VL_ICMS_ST" DOUBLE PRECISION,
    "COD_INF" VARCHAR(255) CHARACTER SET "ISO8859_1",
    "VL_PIS" NUMERIC(15,2),
    "VL_COFINS" NUMERIC(15,2),
    "TP_LIGACAO" VARCHAR(5) CHARACTER SET "ISO8859_1",
    "COD_GRUPO_TENSAO" VARCHAR(5) CHARACTER SET "ISO8859_1",
    "COD_MUN_DEST" VARCHAR(12) CHARACTER SET "ISO8859_1",
    PRIMARY KEY ("PK")
);

-- TABLE: SPEDTMP_C590
CREATE TABLE "SPEDTMP_C590" (
    "PK" INTEGER NOT NULL,
    "FK" INTEGER,
    "CST_ICMS" VARCHAR(6) CHARACTER SET "ISO8859_1",
    "CFOP" VARCHAR(10) CHARACTER SET "ISO8859_1",
    "ALIQ_ICMS" DOUBLE PRECISION,
    "VL_OPR" DOUBLE PRECISION,
    "VL_BC_ICMS" NUMERIC(15,2),
    "VL_ICMS" DOUBLE PRECISION,
    "VL_BC_ICMS_ST" DOUBLE PRECISION,
    "VL_ICMS_ST" DOUBLE PRECISION,
    "VL_RED_BC" NUMERIC(15,2),
    "COD_OBS" VARCHAR(255) CHARACTER SET "ISO8859_1",
    PRIMARY KEY ("PK")
);

-- TABLE: SPEDTMP_D195
CREATE TABLE "SPEDTMP_D195" (
    "PK" INTEGER NOT NULL,
    "FK" INTEGER,
    "ID" INTEGER,
    "COD_OBS" VARCHAR(6) CHARACTER SET "ISO8859_1",
    "TXT_COMPL" VARCHAR(255) CHARACTER SET "ISO8859_1",
    "DESCRICAO_OBS" VARCHAR(47) CHARACTER SET "ISO8859_1",
    "BLOCO195" VARCHAR(11) CHARACTER SET "ISO8859_1",
    PRIMARY KEY ("PK")
);

-- TABLE: SPEDTMP_D197
CREATE TABLE "SPEDTMP_D197" (
    "PK" INTEGER NOT NULL,
    "FK" INTEGER,
    "COD_AJ" VARCHAR(10) CHARACTER SET "ISO8859_1",
    "DESCR_COMPL_AJ" VARCHAR(255) CHARACTER SET "ISO8859_1",
    "COD_ITEM" VARCHAR(255) CHARACTER SET "ISO8859_1",
    "VL_BC_ICMS" DOUBLE PRECISION,
    "ALIQ_ICMS" INTEGER,
    "VL_ICMS" DOUBLE PRECISION,
    "VL_OUTROS" INTEGER,
    PRIMARY KEY ("PK")
);

-- TABLE: SPEDTMP_D500
CREATE TABLE "SPEDTMP_D500" (
    "PK" INTEGER NOT NULL,
    "FK" INTEGER,
    "ID" BIGINT,
    "IND_OPER" INTEGER,
    "IND_EMIT" INTEGER,
    "COD_PART" INTEGER,
    "COD_MOD" VARCHAR(10) CHARACTER SET "ISO8859_1",
    "COD_SIT" VARCHAR(2) CHARACTER SET "ISO8859_1",
    "SER" VARCHAR(20) CHARACTER SET "ISO8859_1",
    "SUB" VARCHAR(255) CHARACTER SET "ISO8859_1",
    "NUM_DOC" VARCHAR(20) CHARACTER SET "ISO8859_1",
    "DT_DOC" TIMESTAMP,
    "DT_A_P" TIMESTAMP,
    "VL_DOC" DOUBLE PRECISION,
    "VL_DESC" DOUBLE PRECISION,
    "VL_SERV" DOUBLE PRECISION,
    "VL_SERV_NT" DOUBLE PRECISION,
    "VL_TERC" DOUBLE PRECISION,
    "VL_DA" DOUBLE PRECISION,
    "VL_BC_ICMS" DOUBLE PRECISION,
    "VL_ICMS" DOUBLE PRECISION,
    "COD_INF" VARCHAR(255) CHARACTER SET "ISO8859_1",
    "VL_PIS" NUMERIC(15,2),
    "VL_COFINS" NUMERIC(15,2),
    "COD_CTA" VARCHAR(255) CHARACTER SET "ISO8859_1",
    "TP_ASSINANTE" VARCHAR(5) CHARACTER SET "ISO8859_1",
    PRIMARY KEY ("PK")
);

-- TABLE: SPEDTMP_D590
CREATE TABLE "SPEDTMP_D590" (
    "PK" INTEGER NOT NULL,
    "FK" INTEGER,
    "CST_ICMS" VARCHAR(6) CHARACTER SET "ISO8859_1",
    "CFOP" VARCHAR(10) CHARACTER SET "ISO8859_1",
    "ALIQ_ICMS" DOUBLE PRECISION,
    "VL_OPR" DOUBLE PRECISION,
    "VL_BC_ICMS" NUMERIC(15,2),
    "VL_ICMS" DOUBLE PRECISION,
    "VL_BC_ICMS_UF" DOUBLE PRECISION,
    "VL_ICMS_UF" DOUBLE PRECISION,
    "VL_RED_BC" NUMERIC(15,2),
    "COD_OBS" VARCHAR(255) CHARACTER SET "ISO8859_1",
    PRIMARY KEY ("PK")
);

-- TABLE: SPEDTMP_E316
CREATE TABLE "SPEDTMP_E316" (
    "PK" INTEGER NOT NULL,
    "FK" INTEGER,
    "UFD" VARCHAR(10) CHARACTER SET "ISO8859_1",
    "COD_OR" VARCHAR(3) CHARACTER SET "ISO8859_1",
    "VL_OR" DOUBLE PRECISION,
    "DT_VCTO" TIMESTAMP,
    "COD_REC" VARCHAR(6) CHARACTER SET "ISO8859_1",
    "MES_REF" VARCHAR(10) CHARACTER SET "ISO8859_1",
    "NUM_PROC" VARCHAR(255) CHARACTER SET "ISO8859_1",
    "IND_PROC" VARCHAR(255) CHARACTER SET "ISO8859_1",
    "PROC" VARCHAR(255) CHARACTER SET "ISO8859_1",
    "TXT_COMP" VARCHAR(255) CHARACTER SET "ISO8859_1",
    PRIMARY KEY ("PK")
);

-- TABLE: SPEDTMP_K100
CREATE TABLE "SPEDTMP_K100" (
    "PK" INTEGER NOT NULL,
    "FK" INTEGER,
    "DT_INI" DATE,
    "DT_FIN" DATE,
    PRIMARY KEY ("PK")
);

-- TABLE: SPEDTMP_K200
CREATE TABLE "SPEDTMP_K200" (
    "PK" INTEGER NOT NULL,
    "FK" INTEGER,
    "DT_EST" DATE,
    "COD_ITEM" INTEGER,
    "QTD" DOUBLE PRECISION,
    "IND_EST" VARCHAR(1) CHARACTER SET "ISO8859_1",
    "COD_PART" VARCHAR(255) CHARACTER SET "ISO8859_1",
    PRIMARY KEY ("PK")
);

-- TABLE: SPEDTMP_K230
CREATE TABLE "SPEDTMP_K230" (
    "PK" INTEGER NOT NULL,
    "FK" INTEGER,
    "ID" INTEGER,
    "DT_INI_OP" DATE,
    "DT_FIN_OP" DATE,
    "COD_DOC_OP" INTEGER,
    "COD_ITEM" INTEGER,
    "QTD_ENC" DOUBLE PRECISION,
    "DT_SAIDA" DATE,
    "COD_ITEM_FILHO" INTEGER,
    "COD_INS_SUBST" INTEGER,
    "QTD" NUMERIC(15,2),
    PRIMARY KEY ("PK")
);

-- TABLE: SPEDTMP_K235
CREATE TABLE "SPEDTMP_K235" (
    "PK" INTEGER NOT NULL,
    "FK" INTEGER,
    "DT_SAIDA" DATE,
    "COD_ITEM" INTEGER,
    "COD_INS_SUBST" INTEGER,
    "QTD" NUMERIC(15,2),
    PRIMARY KEY ("PK")
);


-- ============================================================
-- PROCEDURE: faltando em PROCEL e existentes em BASE_CONFIGURADA
-- ============================================================

-- PROCEDURE: AJUSTAR_C460_DIF_DESC
SET TERM ^ ;
CREATE PROCEDURE "AJUSTAR_C460_DIF_DESC"
(IN "COD_ECF_REDUCAO" INTEGER)
declare variable ID integer;
declare variable PK integer;
declare variable DIF double precision;
declare variable VL_I double precision;
declare variable totalizador_parcial varchar(20);
begin
  for select ID, totalizador_parcial, DIF
      from (select C460.ID, totalizador_parcial,
                   cast(sum(cast(C460.VL_ITEM6 as numeric(12,6))) - sum(cast(C460.VL_ITEM as numeric(12,2))) as numeric(12,2)) as DIF
            from SPEDTMP_C460 C460
            WHERE COD_ECF_REDUCAO = :COD_ECF_REDUCAO
            --WHERE C460.num_doc='33456'
            group by 1,2) TB
      where DIF <> 0
      into :ID, :totalizador_parcial, :DIF
  do
  begin
    for
        select first 1 C460_.PK, C460_.VL_ITEM
        from SPEDTMP_C460 C460_
        where C460_.ID = :ID and C460_.totalizador_parcial = :totalizador_parcial
        order by C460_.VL_ITEM desc, C460_.ALIQ_ICMS desc
        into :PK , :VL_I
    do
    begin
      VL_I = VL_I + :DIF;
      update SPEDTMP_C460
      set VL_ITEM = :VL_I/*, VL_ITEM6 = :VL_I*/
      where PK = :PK;
    end
  end

end^
SET TERM ; ^

-- PROCEDURE: AJUSTA_C460
SET TERM ^ ;
CREATE PROCEDURE "AJUSTA_C460"
(IN "COD_ECF_REDUCAO" INTEGER)
declare variable TOTALIZADOR_AUX varchar(100);
declare variable DIF double precision;
declare variable SOMA double precision;
declare variable PK integer;
declare variable ID integer;
declare variable VL_ITEM double precision;
declare variable DIFTMP double precision;
begin
  for select TOTALIZADOR_AUX, VALOR_ERD - SUM_VL_ITEM as DIF
      from (

      select TOTALIZADOR_AUX, SUM_VL_ITEM,
             (select first 1 VALOR_ACUMULADO
              from ECF_REDUCAO_DETALHE ERD
              where ERD.COD_ECF_REDUCAO = TX.COD_ECF_REDUCAO and
                    ERD.TOTALIZADOR_AUX = TX.TOTALIZADOR_AUX) VALOR_ERD
      from (select COD_ECF_REDUCAO, TOTALIZADOR_AUX, sum(VL_ITEM) SUM_VL_ITEM
            from SPEDTMP_C460 C460
            where COD_ECF_REDUCAO = :COD_ECF_REDUCAO
            group by 1, 2) TX

      ) TX2
      where --tx2.sum_vl_item <> valor_erd and
            VALOR_ERD > 0 and
            ((SUM_VL_ITEM - VALOR_ERD > 0.001) or (SUM_VL_ITEM - VALOR_ERD < -0.001))
      into :TOTALIZADOR_AUX, :DIF
  do
  begin

    for select PK, ID, C460.VL_ITEM
        from SPEDTMP_C460 C460
        where C460.COD_ECF_REDUCAO = :COD_ECF_REDUCAO and
              TOTALIZADOR_AUX = :TOTALIZADOR_AUX
        order by C460.VL_ITEM desc
        into :PK, :ID, :VL_ITEM
    do
    begin
      if ((DIF > 0.001) or (DIF < -0.001)) then
      begin
        if ((DIF < 0) and
            (DIF * -1 > VL_ITEM - 0.001)) then
        begin
          DIFTMP = (VL_ITEM - 0.01) * -1;
          DIF = DIF - DIFTMP;
        end
        else
        begin
          DIFTMP = DIF;
          DIF = 0;
        end
        update SPEDTMP_C460
        set VL_ITEM = round((VL_ITEM + :DIFTMP) * 100) / 100
        where PK = :PK;
        /* insert into LOG_AJUSTE_C460 (PK, ID, DIF)  values (:PK, :ID, :DIFTMP);*/
        update SPEDTMP_C460
        set VL_DOC = (select sum(VL_ITEM)
                      from SPEDTMP_C460
                      where ID = :ID)
        where ID = :ID;
      end
    end
  end

  for select ID, SOMA
      from (select C460.ID, C460.COD_ECF_REDUCAO, C460.NUM_DOC, C460.VL_DOC, sum(C460.VL_ITEM) SOMA
            from SPEDTMP_C460 C460
            group by 1, 2, 3, 4) TB
      where VL_DOC <> SOMA
      into :ID, :SOMA
  do
  begin
    update SPEDTMP_C460
    set VL_DOC = :SOMA
    where ID = :ID;
  end

end^
SET TERM ; ^

-- PROCEDURE: AJUSTA_C460_PISCOFINS
SET TERM ^ ;
CREATE PROCEDURE "AJUSTA_C460_PISCOFINS"
declare variable ID integer;
declare variable VL_PIS double precision;
declare variable VL_COFINS double precision;
begin
  for select ID, VL_PIS_I, VL_COFINS_I
      from (select CC.ID, CC.VL_PIS, CC.VL_COFINS, sum(CC.VL_PIS_I) as VL_PIS_I, sum(CC.VL_COFINS_I) as VL_COFINS_I
            from SPEDTMP_C460 CC
            group by 1, 2, 3) TB
      where (VL_PIS <> VL_PIS_I) or (VL_COFINS <> VL_COFINS_I)
      into :ID, :VL_PIS, :VL_COFINS
  do
  begin
    update SPEDTMP_C460
    set VL_PIS = :VL_PIS,
        VL_COFINS = :VL_COFINS
    where ID = :ID;
  end
end^
SET TERM ; ^

-- PROCEDURE: ECF_REDUCAO_DETALHE_AUX
SET TERM ^ ;
CREATE PROCEDURE "ECF_REDUCAO_DETALHE_AUX"
(IN "COD_ECF_REDUCAO" INTEGER)
declare variable TIPO_TOTALIZADOR varchar(100);
declare variable TOTALIZADOR_PARCIAL varchar(100);
declare variable TOT_AUX varchar(100);
declare variable COD_ECF_REDUCAO_DETALHE integer;
BEGIN
  FOR SELECT COD_ECF_REDUCAO_DETALHE,
    CASE
    WHEN ((TIPO_TOTALIZADOR = 'F') OR (TIPO_TOTALIZADOR = 'F1') OR (TIPO_TOTALIZADOR = 'F2') OR (TIPO_TOTALIZADOR = 'F3')) THEN 'F'
    WHEN ((TIPO_TOTALIZADOR = 'I') OR (TIPO_TOTALIZADOR = 'I1') OR (TIPO_TOTALIZADOR = 'I2') OR (TIPO_TOTALIZADOR = 'I3')) THEN 'I'
    WHEN ((TIPO_TOTALIZADOR = 'N') OR (TIPO_TOTALIZADOR = 'N1') OR (TIPO_TOTALIZADOR = 'N2') OR (TIPO_TOTALIZADOR = 'N3')) THEN 'N'
    WHEN ((TIPO_TOTALIZADOR = 'T')) THEN 'T'|| (SUBSTRING(TOTALIZADOR_PARCIAL FROM 4 FOR 4))
    ELSE TIPO_TOTALIZADOR
    END
  FROM ECF_REDUCAO_DETALHE
  WHERE COD_ECF_REDUCAO = :COD_ECF_REDUCAO
  INTO :COD_ECF_REDUCAO_DETALHE, :TOT_AUX
  DO
  begin
    UPDATE ECF_REDUCAO_DETALHE SET TOTALIZADOR_AUX = :TOT_AUX WHERE COD_ECF_REDUCAO_DETALHE = :COD_ECF_REDUCAO_DETALHE;
    UPDATE ECF_REDUCAO_DETALHE SET TOTALIZADOR_PARCIAL = :TOT_AUX WHERE COD_ECF_REDUCAO_DETALHE = :COD_ECF_REDUCAO_DETALHE AND COALESCE(TOTALIZADOR_PARCIAL,'')='';
  end
END^
SET TERM ; ^

-- PROCEDURE: INTEGRACAO_CARGA_TOTAL_PRODUTOS
SET TERM ^ ;
CREATE PROCEDURE "INTEGRACAO_CARGA_TOTAL_PRODUTOS"
DECLARE variable COD_TAB_PRECO integer;
DECLARE variable COD_FC integer;
DECLARE variable COD_MATERIAL integer;
BEGIN
  SELECT cast(coalesce(VALOR, '0') AS integer) FROM PARAMETRO WHERE NOME_PARAMETRO = 'COD_FRENTE_CAIXA_WEB' INTO :COD_FC;
  SELECT COD_TABELA_PRECO FROM FRENTE_CAIXA WHERE COD_FRENTE_CAIXA = :COD_FC INTO :COD_TAB_PRECO;
  FOR SELECT distinct MTP.COD_MATERIAL
      FROM ALMMATERIAL MAT
      inner join MATERIAL_TAB_PRECO MTP on MTP.COD_MATERIAL = MAT.COD_MATERIAL AND MTP.COD_TABELA_PRECO = :COD_TAB_PRECO
      WHERE ATV_ALMMATERIAL = 'V'
      INTO :COD_MATERIAL
  do
    EXECUTE PROCEDURE SET_FRENTE_CAIXA_PRODUTO(:COD_MATERIAL);
END^
SET TERM ; ^

-- PROCEDURE: PROC_CORRIGE_FIN
SET TERM ^ ;
CREATE PROCEDURE "PROC_CORRIGE_FIN"
declare variable CF integer;
declare variable NPAR integer;
declare variable CHR integer;
begin
  for
    select lf.chave_rel, lf.num_parcela
      from lanc_financeiro lf
     where lf.chave_rel Is not null and cast(lf.dtc_lanc_financeiro as Date) >= '25.04.2012'
     group by lf.chave_rel, lf.num_parcela, lf.complemento_historico
    having count(*) > 1
    into :CHR, :npar
  do begin
    select first 1 lf.cod_fin
      from lanc_financeiro lf
     where lf.chave_rel = :chr
       and lf.num_parcela = :npar
     order by lf.cod_fin desc
      into :CF;

    delete from lanc_conta_fin where cod_fin = :CF;
    delete from cond_pagto where cod_fin = :CF;
    delete from cheque_fin where cod_fin = :CF;
    delete from lanc_financeiro where cod_fin = :CF;
  end
end^
SET TERM ; ^

-- PROCEDURE: PROC_GET_DIV_ESTOQUE_SALDO_0
SET TERM ^ ;
CREATE PROCEDURE "PROC_GET_DIV_ESTOQUE_SALDO_0"
(IN "COD_MATERIAL" VARCHAR(10000), IN "COD_ALMOXARIFADO" VARCHAR(10000), OUT "DESC_DIVISAO" VARCHAR(10000), OUT "QTD" VARCHAR(10000), OUT "TOTAL_QTD" INTEGER)
DECLARE VARIABLE DIV VARCHAR(100);
DECLARE VARIABLE SALDO INTEGER;
DECLARE VARIABLE SQL VARCHAR(5000);
BEGIN
    DESC_DIVISAO = '';
    DIV = '';
    TOTAL_QTD = 0;
    SALDO = 0;
    QTD   = '';
    SQL = 'SELECT   '||
          '    DISTINCT  '||
          '    I.NOME_DIVISAO_ESTOQUE_ITEM,   '||
          '    SUM(PE.SALDO_ATUAL) AS SALDO  '||
          '  FROM DIVISAO_ESTOQUE_ITEM I   '||
          '  INNER JOIN PRODUTO_ESTOQUE PE ON I.COD_DIVISAO_ESTOQUE_ITEM = PE.COD_DIVISAO_ESTOQUE_ITEM   '||
          '  INNER JOIN ALMMATERIAL PRO ON PRO.COD_MATERIAL = PE.COD_MATERIAL '||
          '  WHERE   '||
          '    PE.COD_MATERIAL IN ('||:COD_MATERIAL||')' ||
          '    AND PE.COD_ALMOXARIFADO IN ('||:COD_ALMOXARIFADO||')'||
          '  GROUP BY  I.NOME_DIVISAO_ESTOQUE_ITEM   ORDER BY 1  ';
    IF ((:COD_MATERIAL <> '' )AND (:COD_ALMOXARIFADO <> '')) THEN
    BEGIN
        FOR EXECUTE STATEMENT SQL INTO :DIV, :SALDO DO
        BEGIN
          IF (:DIV <> '') THEN
          BEGIN
            IF ((DESC_DIVISAO = '')AND (QTD='')) THEN
            BEGIN
              DIV = SUBSTRING (DIV FROM (POSITION ('-' IN DIV) + 1) FOR (CHAR_LENGTH(DIV)));
              DESC_DIVISAO = DESC_DIVISAO || CAST(TRIM(SUBSTRING(DIV FROM 1 FOR 4))    AS CHAR(4));
              QTD          = QTD          || CAST(SUBSTRING(SALDO FROM 1 FOR 4) AS CHAR(4));
              TOTAL_QTD = (TOTAL_QTD + :SALDO);
            END
            ELSE
              BEGIN
                DIV = SUBSTRING (DIV FROM (POSITION ('-' IN DIV) + 1) FOR (CHAR_LENGTH(DIV)));
                DESC_DIVISAO = DESC_DIVISAO || '|' || CAST(TRIM(SUBSTRING(DIV FROM 1 FOR 4))   AS CHAR(4));
                QTD          = QTD          || '|' || CAST( SUBSTRING(SALDO FROM 1 FOR 4) AS CHAR(4));
                TOTAL_QTD = TOTAL_QTD + :SALDO;
              END
          END
          SALDO = 0;
          DIV   = '';
        END
        SUSPEND;
      END

END^
SET TERM ; ^

-- PROCEDURE: PROC_REL_ANALITICO_LANC_FIN_DRE
SET TERM ^ ;
CREATE PROCEDURE "PROC_REL_ANALITICO_LANC_FIN_DRE"
(IN "PEFETIVACAOINICIAL" VARCHAR(1000), IN "PEFETIVACAOFINAL" VARCHAR(1000), IN "PCONCILIACAOINICIAL" VARCHAR(1000), IN "PCONCILIACAOFINAL" VARCHAR(1000), IN "PDISPONIVELINICIAL" VARCHAR(1000), IN "PDISPONIVELFINAL" VARCHAR(1000), IN "PCONTAFINANCEIRA" VARCHAR(1000), IN "PHISTORICO" VARCHAR(1000), IN "PCONTACONTABIL" VARCHAR(1000), IN "PCENTROCUSTO" VARCHAR(1000), IN "PEMPRESA" VARCHAR(1000))
DECLARE VARIABLE P_NOME_CC VARCHAR(100);
DECLARE VARIABLE P_NOME_HISTORICO VARCHAR(100);
DECLARE VARIABLE P_NOME_CONTA_FINANCEIRA VARCHAR(100);
DECLARE VARIABLE P_VALOR_ENTRADA DOUBLE PRECISION;
DECLARE VARIABLE P_VALOR_SAIDA DOUBLE PRECISION;
DECLARE VARIABLE P_NOME_PLANO_CONTA VARCHAR(100);
DECLARE VARIABLE P_COD_PLANO_CONTA VARCHAR(100);
DECLARE VARIABLE P_COD_CONTABIL VARCHAR(100);
DECLARE VARIABLE P_NUM_DOC VARCHAR(20);
DECLARE VARIABLE P_COMPLEMENTO_HISTORICO VARCHAR(200);
DECLARE VARIABLE P_DATA_DISPONIVEL DATE;
DECLARE VARIABLE P_SALDO_DISPONIVEL DOUBLE PRECISION;
DECLARE VARIABLE INDICE INTEGER;
DECLARE VARIABLE SALDODISPONIVELCALCULADO DOUBLE PRECISION;
DECLARE VARIABLE V_SQL VARCHAR(5000);
DECLARE VARIABLE V_SQL2 VARCHAR(5000);
DECLARE VARIABLE V_FILTROS VARCHAR(1000);
DECLARE VARIABLE V_FILTROS2 VARCHAR(1000);
DECLARE VARIABLE P_SALDO_INICIAL DOUBLE PRECISION;
DECLARE VARIABLE P_LANCAMENTO_ESTORNADO VARCHAR(3);
DECLARE VARIABLE P_COD_LANC_CONTA_FIN INTEGER;
DECLARE VARIABLE VCOD_CONTA_FIN VARCHAR(10);
DECLARE VARIABLE VCOD_CONTA INTEGER;
DECLARE VARIABLE VCONTAFINANCEIRA VARCHAR(2500);
DECLARE VARIABLE P_TIPO INTEGER;
DECLARE VARIABLE P_NUM_NF VARCHAR(100);
DECLARE VARIABLE P_TRANSF_ORIGEM VARCHAR(100);
DECLARE VARIABLE P_TRANSF_DESTINO VARCHAR(100);
DECLARE VARIABLE P_DATA_DIS TIMESTAMP;
DECLARE VARIABLE P_JURO DOUBLE PRECISION;
DECLARE VARIABLE P_MULTA DOUBLE PRECISION;
DECLARE VARIABLE P_SALDO_MOVTO_DIA NUMERICO_15_4;
DECLARE VARIABLE V_SALDO_MOVTO_DIA NUMERICO_15_4;
DECLARE VARIABLE P_DESCONTO DOUBLE PRECISION;
DECLARE VARIABLE P_COD_CONTA_FINANCEIRA INTEGER;
DECLARE VARIABLE P_DATA_BAIXA DATE;
DECLARE VARIABLE P_NOME_CENTRO_CUSTO VARCHAR(100);
DECLARE VARIABLE P_OBS_LANC_FIN BLOB SUB_TYPE 0 SEGMENT SIZE 80;
DECLARE VARIABLE P_COD_FIN INTEGER;
DECLARE VARIABLE P_DATA_PAGAMENTO DATE;
DECLARE VARIABLE P_NOME_FORMA_PAGTO VARCHAR(100);
BEGIN
  VCOD_CONTA_FIN = 0;
  V_SALDO_MOVTO_DIA = 0;
  P_SALDO_MOVTO_DIA = 0;
  VCOD_CONTA = 0;
  VCONTAFINANCEIRA = '';
  P_DATA_DIS = CURRENT_DATE;

  EXECUTE PROCEDURE PROC_LIMPA_TABELA('REL_ANALITICO_LANC_FIN');

  IF (PCONTAFINANCEIRA <> '') THEN
    VCONTAFINANCEIRA = PCONTAFINANCEIRA;

  IF (PCONTAFINANCEIRA = '') THEN
  BEGIN
    VCONTAFINANCEIRA = '';
    FOR SELECT CFI.COD_CONTA_FINANCEIRA
          FROM CONTA_FINANCEIRA CFI
         WHERE CFI.ATV_CONTA_FINANCEIRA = 'V'
       INTO :VCOD_CONTA DO
       BEGIN
         IF (VCONTAFINANCEIRA = '') THEN
           VCONTAFINANCEIRA = :VCOD_CONTA;
         ELSE
         IF (VCONTAFINANCEIRA <> '') THEN
           VCONTAFINANCEIRA = VCONTAFINANCEIRA ||','|| :VCOD_CONTA;
       END
  END

  V_SQL = 'SELECT CFI.COD_CONTA_FINANCEIRA
        FROM CONTA_FINANCEIRA CFI
       WHERE CFI.ATV_CONTA_FINANCEIRA = '||'''V'''||
       ' AND CFI.COD_CONTA_FINANCEIRA IN ('||:VCONTAFINANCEIRA||')';

  FOR EXECUTE STATEMENT V_SQL
       INTO :VCOD_CONTA_FIN DO
  BEGIN
      INDICE = 0;
      SALDODISPONIVELCALCULADO = 0;
      V_FILTROS = '';
      V_FILTROS2 = '';
      IF (PEFETIVACAOINICIAL<>'') THEN
        V_FILTROS = V_FILTROS ||' AND LCF.DATA_EFETIVACAO >= '||''''||PEFETIVACAOINICIAL||'''';
      IF (PEFETIVACAOFINAL<>'') THEN
        V_FILTROS = V_FILTROS ||' AND LCF.DATA_EFETIVACAO <='||''''||PEFETIVACAOFINAL||'''';
      IF (PCONCILIACAOINICIAL<>'') THEN
        V_FILTROS = V_FILTROS ||' AND LCF.DATA_CONCILIACAO >='||''''||PCONCILIACAOINICIAL||'''';
      IF (PCONCILIACAOFINAL<>'') THEN
        V_FILTROS = V_FILTROS ||' AND LCF.DATA_CONCILIACAO <='||''''||PCONCILIACAOFINAL||'''';
      IF (PDISPONIVELINICIAL<>'') THEN
        V_FILTROS = V_FILTROS ||' AND LCF.DATA_DISPONIVEL >='||''''||PDISPONIVELINICIAL||'''';
      IF (PDISPONIVELFINAL<>'') THEN
        V_FILTROS = V_FILTROS ||' AND LCF.DATA_DISPONIVEL <='||''''||PDISPONIVELFINAL||'''';
      --IF (PCONTAFINANCEIRA<>'') THEN
        V_FILTROS = V_FILTROS ||' AND LCF.COD_CONTA_FINANCEIRA IN ('||VCOD_CONTA_FIN||')';
      IF (PHISTORICO<>'') THEN
        V_FILTROS = V_FILTROS ||' AND LCF.COD_HISTORICO IN ('||PHISTORICO||')';
      IF (PCONTACONTABIL<>'') THEN
        V_FILTROS = V_FILTROS ||' AND LCF.COD_PLANO_CONTA IN ('||PCONTACONTABIL||')';
      IF (PCENTROCUSTO<>'') THEN
        V_FILTROS = V_FILTROS ||' AND LCF.COD_CENTRO_CUSTO IN ('||PCENTROCUSTO||')';
      IF (PEMPRESA<>'') THEN
        V_FILTROS = V_FILTROS ||' AND LCF.COD_EMPRESA_FIN IN ('||PEMPRESA||')';
    
      IF (PDISPONIVELINICIAL<>'') THEN
        V_FILTROS2 = V_FILTROS2 ||' AND LCFS.DATA_DISPONIVEL <'||''''||PDISPONIVELINICIAL||'''';
      --IF (PCONTAFINANCEIRA<>'') THEN
        V_FILTROS2 = V_FILTROS2 ||' AND LCFS.COD_CONTA_FINANCEIRA IN ('||VCOD_CONTA_FIN||')';

     V_SQL2 = '
     SELECT
     FIRST 1 CAST(LCF.DATA_DISPONIVEL AS DATE)
     FROM LANC_CONTA_FIN LCF
            INNER JOIN CONTA_FINANCEIRA C ON LCF.COD_CONTA_FINANCEIRA=C.COD_CONTA_FINANCEIRA
            LEFT  JOIN LANC_FINANCEIRO LF ON LCF.COD_FIN=LF.COD_FIN
            LEFT  JOIN GERFORNECEDOR F    ON LF.COD_FORNECEDOR=F.COD_FORNECEDOR
            LEFT  JOIN VTCENTRO_CUSTO CC  ON LF.COD_CC=CC.COD_CC
            LEFT  JOIN HISTORICO H        ON LCF.COD_HISTORICO=H.COD_HISTORICO
            LEFT  JOIN PLANO_CONTA PC     ON LCF.COD_PLANO_CONTA=PC.COD_PLANO_CONTA
            LEFT  JOIN LANC_CONTA_FIN_SALDO LCFS ON LCF.COD_CONTA_FINANCEIRA=LCFS.COD_CONTA_FINANCEIRA AND LCF.DATA_DISPONIVEL=LCFS.DATA_DISPONIVEL
            LEFT  JOIN TIPO_REALIZACAO  REA ON REA.COD_TIPO_REALIZACAO = LCF.COD_TIPO_REALIZACAO
     WHERE LCF.COD_LANC_CONTA_FIN <> 0 AND  PC.USAR_NO_REL_FIN = ''V'''
     ||V_FILTROS||'
     ORDER BY LCF.DATA_DISPONIVEL, LCF.COD_LANC_CONTA_FIN';

     EXECUTE STATEMENT V_SQL2 INTO :P_DATA_DIS;

      V_SQL = '';
    
      V_SQL = 'SELECT FIRST 1 COALESCE(LCFS.SALDO_DISPONIVEL, 0) TOTAL
               FROM LANC_CONTA_FIN_SALDO LCFS
               WHERE COD_LANC_CONTA_FIN_SALDO > 0 AND LCFS.data_disponivel < '  ||''''||CAST(P_DATA_DIS AS DATE)||'''' ||'
              '||V_FILTROS2||'
               ORDER BY LCFS.DATA_DISPONIVEL DESC';
    
      EXECUTE STATEMENT V_SQL INTO :P_SALDO_INICIAL;
    
      IF (P_SALDO_INICIAL IS NULL) THEN
        P_SALDO_INICIAL = 0;
    
      V_SQL = '';
    
      V_SQL = 'SELECT
                 CASE WHEN (NOT LF.COD_FORNECEDOR IS NULL) THEN
                       F.NOME_FORNECEDOR
                     ELSE
                       CC.NOME_CC
                  END AS NOME_CC,
                   H.NOME_HISTORICO,
                   C.NOME_CONTA_FINANCEIRA,
                   C.COD_CONTA_FINANCEIRA,
                   LF.DATA_LANC_BAIXA,
                   CASE WHEN LF.DATA_PAGAMENTO IS NULL THEN
                       LCF.DATA_EFETIVACAO
                   ELSE
                      LF.DATA_PAGAMENTO
                   END DATA_PAGAMENTO,
                   CEC.NOME_CENTRO_CUSTO,
                   LF.OBS_LANC,
                   LCF.COD_FIN,
                   LCF.VALOR_ENTRADA,
                   COALESCE(LCF.VALOR_SAIDA,0) AS VALOR_SAIDA,
                   ('||:P_SALDO_MOVTO_DIA||' + LCF.VALOR_ENTRADA - LCF.VALOR_SAIDA) SALDO_MOVTO_DIA,
                   PC.COD_PLANO_CONTA,
                   PC.NOME_PLANO_CONTA,
                   PC.CODIGO_CONTABIL,
                   LF.NUM_DOC,
                   LCF.COMPLEMENTO_HISTORICO,
                   LCF.DATA_DISPONIVEL,
                   COALESCE( LCFS.SALDO_DISPONIVEL,0)SALDO_DISPONIVEL,
             CASE WHEN ((LCF.reg_estorno is not null) OR (LCF.LANCAMENTO_ESTORNADO = ''V'')) THEN
                   '||''''||'SIM'||''''||'
                 ELSE
                   '||''''||''''||'
               END AS LANCAMENTO_ESTORNADO,
               LCF.COD_LANC_CONTA_FIN,
                CASE WHEN (LCF.VALOR_ENTRADA  > 0 ) THEN
                 C.NOME_CONTA_FINANCEIRA
               END AS TRANSF_DESTINO,
               CASE WHEN (LCF.VALOR_SAIDA > 0 ) THEN
                 C.NOME_CONTA_FINANCEIRA
               END AS TRANSF_ORIGEM,
               REA.NOME_TIPO_REALIZACAO,
               (SELECT VP.NUMERO_NF FROM VENDA_PRODUTO VP WHERE VP.COD_VENDA = LF.CHAVE_REL),
               LCF.VALOR_JURO,
               LCF.VALOR_MULTA,
               LCF.VALOR_DESCONTO,
               FP.NOME_FORMA_PAGTO
            FROM LANC_CONTA_FIN LCF
                   INNER JOIN CONTA_FINANCEIRA C ON LCF.COD_CONTA_FINANCEIRA=C.COD_CONTA_FINANCEIRA
                   LEFT  JOIN FORMA_PAGTO FP ON FP.COD_FORMA_PAGTO = LCF.COD_FORMA_PAGTO
                   LEFT  JOIN LANC_FINANCEIRO LF ON LCF.COD_FIN=LF.COD_FIN
                   LEFT  JOIN GERFORNECEDOR F    ON LF.COD_FORNECEDOR=F.COD_FORNECEDOR
                   LEFT  JOIN VTCENTRO_CUSTO CC  ON LF.COD_CC=CC.COD_CC
                   LEFT  JOIN HISTORICO H        ON LCF.COD_HISTORICO=H.COD_HISTORICO
                   LEFT  JOIN PLANO_CONTA PC     ON LCF.COD_PLANO_CONTA=PC.COD_PLANO_CONTA
                   LEFT  JOIN CENTRO_CUSTO CEC   ON CEC.COD_CENTRO_CUSTO = LCF.COD_CENTRO_CUSTO
                   LEFT  JOIN LANC_CONTA_FIN_SALDO LCFS ON LCF.COD_CONTA_FINANCEIRA=LCFS.COD_CONTA_FINANCEIRA AND LCF.DATA_DISPONIVEL=LCFS.DATA_DISPONIVEL
                   LEFT  JOIN TIPO_REALIZACAO  REA ON REA.COD_TIPO_REALIZACAO = LCF.COD_TIPO_REALIZACAO
            WHERE LCF.COD_LANC_CONTA_FIN <> 0
                  AND PC.USAR_NO_REL_FIN = ''V'''
            ||V_FILTROS||'
            ORDER BY LCF.DATA_DISPONIVEL, LCF.COD_LANC_CONTA_FIN';
    
      FOR EXECUTE STATEMENT V_SQL
            INTO :P_NOME_CC, :P_NOME_HISTORICO, :P_NOME_CONTA_FINANCEIRA,:P_COD_CONTA_FINANCEIRA,:P_DATA_BAIXA,:P_DATA_PAGAMENTO,:P_NOME_CENTRO_CUSTO,:P_OBS_LANC_FIN,:P_COD_FIN,
             :P_VALOR_ENTRADA, :P_VALOR_SAIDA, :P_SALDO_MOVTO_DIA, :P_COD_PLANO_CONTA, :P_NOME_PLANO_CONTA, :P_COD_CONTABIL, :P_NUM_DOC, :P_COMPLEMENTO_HISTORICO, :P_DATA_DISPONIVEL,
             :P_SALDO_DISPONIVEL,:P_LANCAMENTO_ESTORNADO, :P_COD_LANC_CONTA_FIN, :P_TRANSF_DESTINO, :P_TRANSF_ORIGEM, :P_TIPO, :P_NUM_NF, :P_JURO, :P_MULTA, :P_DESCONTO ,:P_NOME_FORMA_PAGTO

             DO
      BEGIN
        INDICE = INDICE + 1;
        V_SALDO_MOVTO_DIA = :P_SALDO_MOVTO_DIA + V_SALDO_MOVTO_DIA;
    
        IF (INDICE = 1) THEN
          SALDODISPONIVELCALCULADO = P_SALDO_INICIAL + :P_VALOR_ENTRADA - :P_VALOR_SAIDA;
        ELSE
          SALDODISPONIVELCALCULADO = SALDODISPONIVELCALCULADO + :P_VALOR_ENTRADA - :P_VALOR_SAIDA;
    
        INSERT INTO REL_ANALITICO_LANC_FIN(INDICE, NOME_CC, NOME_HISTORICO, NOME_CONTA_FINANCEIRA, VALOR_ENTRADA, VALOR_SAIDA,
                                          COD_PLANO_CONTA, NOME_PLANO_CONTA, CLASSIFICADOR_CONTABIL, NUM_DOC, COMPLEMENTO_HISTORICO, DATA_DISPONIVEL, SALDO_DISPONIVEL,SALDO_INICIAL,SALDO_DISP_CALCULADO, LANCAMENTO_ESTORNADO,
                                          COD_LANC_CONTA_FIN, TRANSF_DESTINO, TRANSF_ORIGEM, TIPO, NUM_NF, JURO, MULTA, DESCONTO ,COD_CONTA_FINANCEIRA, DATA_LANC_BAIXA, NOME_CENTRO_CUSTO,OBS_LANC,COD_FIN,DATA_PAGAMENTO, NOME_FORMA_PAGTO, SALDO_MOVTO_DIA )
                                          VALUES
                                          (:INDICE, :P_NOME_CC, :P_NOME_HISTORICO, :P_NOME_CONTA_FINANCEIRA, :P_VALOR_ENTRADA, :P_VALOR_SAIDA,
                                           :P_COD_PLANO_CONTA, :P_NOME_PLANO_CONTA, :P_COD_CONTABIL, :P_NUM_DOC, :P_COMPLEMENTO_HISTORICO, :P_DATA_DISPONIVEL,:P_SALDO_DISPONIVEL,:P_SALDO_INICIAL,:SALDODISPONIVELCALCULADO, :P_LANCAMENTO_ESTORNADO,
                                           :P_COD_LANC_CONTA_FIN, :P_TRANSF_DESTINO, :P_TRANSF_ORIGEM, :P_TIPO, :P_NUM_NF, :P_JURO, :P_MULTA, :P_DESCONTO,:P_COD_CONTA_FINANCEIRA,:P_DATA_BAIXA,:P_NOME_CENTRO_CUSTO,:P_OBS_LANC_FIN ,:p_cod_fin, :P_DATA_PAGAMENTO, :P_NOME_FORMA_PAGTO,:V_SALDO_MOVTO_DIA);
      END
  END
END^
SET TERM ; ^

-- PROCEDURE: SET_FRENTE_CAIXA_PRODUTO
SET TERM ^ ;
CREATE PROCEDURE "SET_FRENTE_CAIXA_PRODUTO"
(IN "COD_MATERIAL" INTEGER)
declare variable COD_FRENTE_CAIXA_WEB integer;
declare variable S varchar(100);
declare variable COD_TP integer;
declare variable QT integer;
begin
  select coalesce(trim(VALOR), '0')
  from PARAMETRO PP
  where PP.NOME_PARAMETRO = 'COD_FRENTE_CAIXA_WEB'
  into :S;
  if (:S <> '') then
  begin
    COD_FRENTE_CAIXA_WEB = cast(S as integer);
    select cod_tabela_preco from frente_caixa where cod_frente_caixa=:cod_frente_caixa_web into cod_tp;
    select count(*) from material_tab_preco where cod_material = :cod_material and cod_tabela_preco = :cod_tp into qt;
    if (qt>0) then
    update or insert into FRENTE_CAIXA_PRODUTO (COD_MATERIAL, COD_FRENTE_CAIXA)
    values (:COD_MATERIAL, :COD_FRENTE_CAIXA_WEB)
    matching (COD_MATERIAL, COD_FRENTE_CAIXA);
  end
end^
SET TERM ; ^

-- PROCEDURE: SPEDTMP_TOTAIS_C100
SET TERM ^ ;
CREATE PROCEDURE "SPEDTMP_TOTAIS_C100"
(IN "ID" INTEGER)
declare variable C170_VL_DESC numeric(15,2);
declare variable C170_VL_ITEM numeric(15,2);
declare variable C170_VVL_OUT_DA numeric(15,2);
declare variable C190_VL_BC_ICMS numeric(15,2);
declare variable C190_VL_ICMS numeric(15,2);
declare variable C190_VL_BC_ICMS_ST numeric(15,2);
declare variable C190_VL_ICMS_ST numeric(15,2);
declare variable C170_VL_PIS numeric(15,2);
declare variable C170_VL_COFINS numeric(15,2);
declare variable C190_VL_IPI numeric(15,2);
begin

   select
       sum(C170.VL_DESC),
       sum(C170.VL_ITEM),
       sum(C170.VL_PIS),
       sum(C170.VL_COFINS),
       sum(C170.VL_OUT_DA)
   from SPEDTMP_C170 C170
   where C170.ID = :ID
   into :C170_VL_DESC,
        :C170_VL_ITEM,
        :C170_VL_PIS,
        :C170_VL_COFINS,
        :C170_VVL_OUT_DA;

   select
       sum(C190.VL_BC_ICMS),
       sum(C190.VL_ICMS),
       sum(C190.VL_BC_ICMS_ST),
       sum(C190.VL_ICMS_ST),
       sum(C190.VL_IPI)
   from SPEDTMP_C190 C190
   where C190.ID = :ID
   into :C190_VL_BC_ICMS,
        :C190_VL_ICMS,
        :C190_VL_BC_ICMS_ST,
        :C190_VL_ICMS_ST,
        :C190_VL_IPI;

   update SPEDTMP_C100 C100
   set C100.VL_DESC = :C170_VL_DESC,
       C100.VL_MERC = :C170_VL_ITEM,
       C100.VL_OUT_DA = C100.VL_OUT_DA + :C170_VVL_OUT_DA,
       C100.VL_BC_ICMS = :C190_VL_BC_ICMS,
       C100.VL_ICMS = :C190_VL_ICMS,
       C100.VL_BC_ICMS_ST = :C190_VL_BC_ICMS_ST,
       C100.VL_ICMS_ST = :C190_VL_ICMS_ST,
       C100.VL_PIS = :C170_VL_PIS,
       C100.VL_COFINS = :C170_VL_COFINS,
       C100.VL_IPI = :C190_VL_IPI
   where C100.ID = :ID;

   suspend;
end^
SET TERM ; ^

-- PROCEDURE: SP_ASSOCIAR_BENEFICIO_PADRAO
SET TERM ^ ;
CREATE PROCEDURE "SP_ASSOCIAR_BENEFICIO_PADRAO"
(OUT "REGISTROS_ASSOCIADOS" INTEGER)
DECLARE VARIABLE V_COD_NATUREZA INTEGER;
BEGIN
    REGISTROS_ASSOCIADOS = 0;
    
    /* Associar o benefício padrão para naturezas sem benefício */
    FOR SELECT 
            N.COD_NATUREZA_OPER
        FROM 
            NATUREZA_OPER N
        WHERE 
            NOT EXISTS (
                SELECT 1 FROM NATUREZA_OPER_BENEF_FISCAL 
                WHERE COD_NATUREZA_OPER = N.COD_NATUREZA_OPER
            )
        INTO 
            :V_COD_NATUREZA
    DO
    BEGIN
        INSERT INTO NATUREZA_OPER_BENEF_FISCAL (
            COD_NATUREZA_OPER, 
            COD_BENEFICIO
        ) VALUES (
            :V_COD_NATUREZA, 
            0
        );
        
        REGISTROS_ASSOCIADOS = REGISTROS_ASSOCIADOS + 1;
    END
    
    SUSPEND;
END^
SET TERM ; ^

-- PROCEDURE: SP_BENEF_NAT
SET TERM ^ ;
CREATE PROCEDURE "SP_BENEF_NAT"
(IN "IN_COD_NATUREZA" INTEGER, OUT "COD_NATUREZA_OPER" INTEGER, OUT "COD_BENEFICIO" INTEGER, OUT "ID_BENEFICIO" VARCHAR(20), OUT "NOME_BENEFICIO" VARCHAR(100))
BEGIN
    FOR SELECT 
        COD_NATUREZA_OPER,
        COD_BENEFICIO,
        ID_BENEFICIO,
        NOME_BENEFICIO
    FROM 
        SP_NAT_BENEF(:IN_COD_NATUREZA)
    INTO 
        :COD_NATUREZA_OPER, :COD_BENEFICIO, :ID_BENEFICIO, :NOME_BENEFICIO
    DO
        SUSPEND;
END^
SET TERM ; ^

-- PROCEDURE: SP_BUSCA_NATUREZA_OPERACAO
SET TERM ^ ;
CREATE PROCEDURE "SP_BUSCA_NATUREZA_OPERACAO"
(IN "IN_COD_NATUREZA" INTEGER, OUT "COD_NATUREZA_OPER_CST" INTEGER, OUT "NOME_SUBST_TRIBUTARIA" VARCHAR(100), OUT "NOME_SUBST_TRIBUTARIA_TRAT" VARCHAR(100))
BEGIN
    /* Sua lógica SQL aqui */
    FOR SELECT NOC.COD_NATUREZA_OPER_CST,
               ST1.ID_SUBST_TRIBUTARIA || ' - ' || ST1.NOME_SUBST_TRIBUTARIA,
               ST2.ID_SUBST_TRIBUTARIA || ' - ' || ST2.NOME_SUBST_TRIBUTARIA
        FROM NATUREZA_OPER_CST NOC
        LEFT JOIN SUBST_TRIBUTARIA ST1 ON NOC.COD_SUBST_TRIBUTARIA = ST1.COD_SUBST_TRIBUTARIA
        LEFT JOIN SUBST_TRIBUTARIA ST2 ON NOC.COD_SUBST_TRIBUTARIA_TRATAMENTO = ST2.COD_SUBST_TRIBUTARIA
        WHERE NOC.COD_NATUREZA_OPER = :IN_COD_NATUREZA
        INTO :COD_NATUREZA_OPER_CST, :NOME_SUBST_TRIBUTARIA, :NOME_SUBST_TRIBUTARIA_TRAT
    DO
        SUSPEND;
END^
SET TERM ; ^

-- PROCEDURE: SP_CONSULTA_NATUREZA_OPERACAO
SET TERM ^ ;
CREATE PROCEDURE "SP_CONSULTA_NATUREZA_OPERACAO"
(IN "IN_COD_NATUREZA" INTEGER, OUT "COD_NATUREZA_OPER_CST" INTEGER, OUT "NOME_SUBST_TRIBUTARIA" VARCHAR(100), OUT "NOME_SUBST_TRIBUTARIA_TRAT" VARCHAR(100))
BEGIN
    FOR SELECT NOC.COD_NATUREZA_OPER_CST,
               ST1.ID_SUBST_TRIBUTARIA || ' - ' || ST1.NOME_SUBST_TRIBUTARIA,
               ST2.ID_SUBST_TRIBUTARIA || ' - ' || ST2.NOME_SUBST_TRIBUTARIA
        FROM NATUREZA_OPER_CST NOC
        LEFT JOIN SUBST_TRIBUTARIA ST1 ON NOC.COD_SUBST_TRIBUTARIA = ST1.COD_SUBST_TRIBUTARIA
        LEFT JOIN SUBST_TRIBUTARIA ST2 ON NOC.COD_SUBST_TRIBUTARIA_TRATAMENTO = ST2.COD_SUBST_TRIBUTARIA
        WHERE NOC.COD_NATUREZA_OPER = :IN_COD_NATUREZA
        INTO :COD_NATUREZA_OPER_CST, :NOME_SUBST_TRIBUTARIA, :NOME_SUBST_TRIBUTARIA_TRAT
    DO
        SUSPEND;
END^
SET TERM ; ^

-- PROCEDURE: SP_DEPURA_NATUREZA
SET TERM ^ ;
CREATE PROCEDURE "SP_DEPURA_NATUREZA"
(IN "IN_COD_NATUREZA" INTEGER, OUT "COD_NATUREZA_OPER" INTEGER, OUT "NOME_NATUREZA_OPER" VARCHAR(100))
BEGIN
    /* Procedure simplificada apenas para teste */
    FOR SELECT 
        COD_NATUREZA_OPER,
        NOME_NATUREZA_OPER
    FROM 
        NATUREZA_OPER
    WHERE 
        COD_NATUREZA_OPER = :IN_COD_NATUREZA
    INTO 
        :COD_NATUREZA_OPER, :NOME_NATUREZA_OPER
    DO
        SUSPEND;
END^
SET TERM ; ^

-- PROCEDURE: SP_FIX_BENEFICIO_FISCAL
SET TERM ^ ;
CREATE PROCEDURE "SP_FIX_BENEFICIO_FISCAL"
(IN "IN_COD_NATUREZA" INTEGER, OUT "COD_NATUREZA_OPER" INTEGER, OUT "COD_BENEF_FISCAL" INTEGER, OUT "NOME_BENEF_FISCAL" VARCHAR(100))
BEGIN
  /* Use apenas as tabelas que realmente existem no seu banco */
  SELECT 
    N.COD_NATUREZA_OPER,
    CAST(0 AS INTEGER) AS COD_BENEF_FISCAL,
    CAST('NENHUM BENEFÍCIO' AS VARCHAR(100)) AS NOME_BENEF_FISCAL
  FROM 
    NATUREZA_OPER N
  WHERE 
    N.COD_NATUREZA_OPER = :IN_COD_NATUREZA
  INTO 
    :COD_NATUREZA_OPER, :COD_BENEF_FISCAL, :NOME_BENEF_FISCAL;
  
  SUSPEND;
END^
SET TERM ; ^

-- PROCEDURE: SP_GET_BENEFICIOS_NATUREZA
SET TERM ^ ;
CREATE PROCEDURE "SP_GET_BENEFICIOS_NATUREZA"
(IN "IN_COD_NATUREZA" INTEGER, OUT "COD_NATUREZA_OPER" INTEGER, OUT "COD_BENEFICIO" INTEGER, OUT "ID_BENEFICIO" VARCHAR(20), OUT "NOME_BENEFICIO" VARCHAR(100))
BEGIN
    /* Primeiro tentamos obter benefícios reais */
    FOR SELECT 
        NOBF.COD_NATUREZA_OPER,
        BF.COD_BENEFICIO,
        BF.ID_BENEFICIO,
        BF.NOME_BENEFICIO
    FROM 
        BENEFICIO_FISCAL BF
        JOIN NATUREZA_OPER_BENEF_FISCAL NOBF ON BF.COD_BENEFICIO = NOBF.COD_BENEFICIO
    WHERE 
        NOBF.COD_NATUREZA_OPER = :IN_COD_NATUREZA
    INTO 
        :COD_NATUREZA_OPER, :COD_BENEFICIO, :ID_BENEFICIO, :NOME_BENEFICIO
    DO
        SUSPEND;
    
    /* Se não encontrou nenhum benefício, retorna um registro fictício */
    IF (ROW_COUNT = 0) THEN
    BEGIN
        /* Sempre retorna algo para evitar o erro */
        SELECT 
            COALESCE(:IN_COD_NATUREZA, 0),
            BF.COD_BENEFICIO,
            BF.ID_BENEFICIO,
            BF.NOME_BENEFICIO
        FROM 
            BENEFICIO_FISCAL BF
        WHERE 
            BF.COD_BENEFICIO = 0
        INTO 
            :COD_NATUREZA_OPER, :COD_BENEFICIO, :ID_BENEFICIO, :NOME_BENEFICIO;
        
        SUSPEND;
    END
END^
SET TERM ; ^

-- PROCEDURE: SP_MIGRAR_BENEFICIOS
SET TERM ^ ;
CREATE PROCEDURE "SP_MIGRAR_BENEFICIOS"
(OUT "REGISTROS_MIGRADOS" INTEGER)
DECLARE VARIABLE V_COD_NATUREZA INTEGER;
DECLARE VARIABLE V_COD_SUBST_TRIBUTARIA INTEGER;
DECLARE VARIABLE V_CBENEF VARCHAR(10);
DECLARE VARIABLE V_COD_BENEFICIO INTEGER;
BEGIN
    REGISTROS_MIGRADOS = 0;
    
    /* Migrar dados da tabela NATUREZA_BENEFICIO_FISCAL para NATUREZA_OPER_BENEF_FISCAL */
    FOR SELECT 
            NBF.COD_NATUREZA_OPER,
            NBF.COD_SUBST_TRIBUTARIA,
            NBF.CBENEF
        FROM 
            NATUREZA_BENEFICIO_FISCAL NBF
        INTO 
            :V_COD_NATUREZA, :V_COD_SUBST_TRIBUTARIA, :V_CBENEF
    DO
    BEGIN
        /* Verificar se já existe um benefício com esse CBENEF */
        SELECT FIRST 1 
            BF.COD_BENEFICIO 
        FROM 
            BENEFICIO_FISCAL BF 
        WHERE 
            BF.ID_BENEFICIO = :V_CBENEF
        INTO 
            :V_COD_BENEFICIO;
        
        /* Se não existe, criar */
        IF (V_COD_BENEFICIO IS NULL) THEN
        BEGIN
            /* Criar novo benefício fiscal */
            INSERT INTO BENEFICIO_FISCAL (
                ID_BENEFICIO, 
                NOME_BENEFICIO, 
                ICMS_SUBST_TRIB
            )
            VALUES (
                :V_CBENEF,
                'Benefício ' || :V_CBENEF,
                'S'
            );
            
            /* Obter o ID gerado */
            V_COD_BENEFICIO = GEN_ID(SEQ_BENEFICIO_FISCAL, 0);
        END
        
        /* Associar à natureza */
        IF (NOT EXISTS(
            SELECT 1 FROM NATUREZA_OPER_BENEF_FISCAL 
            WHERE COD_NATUREZA_OPER = :V_COD_NATUREZA 
            AND COD_BENEFICIO = :V_COD_BENEFICIO
        )) THEN
        BEGIN
            INSERT INTO NATUREZA_OPER_BENEF_FISCAL (
                COD_NATUREZA_OPER, 
                COD_BENEFICIO
            ) VALUES (
                :V_COD_NATUREZA, 
                :V_COD_BENEFICIO
            );
            
            REGISTROS_MIGRADOS = REGISTROS_MIGRADOS + 1;
        END
    END
    
    SUSPEND;
END^
SET TERM ; ^

-- PROCEDURE: SP_NATUREZA_BENEFICIO
SET TERM ^ ;
CREATE PROCEDURE "SP_NATUREZA_BENEFICIO"
(IN "IN_COD_NATUREZA" INTEGER, OUT "COD_BENEFICIO" INTEGER, OUT "ID_BENEFICIO" VARCHAR(20), OUT "NOME_BENEFICIO" VARCHAR(100), OUT "ICMS_SUBST_TRIB" CHAR(1), OUT "TRATA_ICMS_NORMAL" CHAR(1), OUT "TRATA_PIS_COFINS" CHAR(1), OUT "DESCONTA_BASE_ICMS" CHAR(1), OUT "DESCONTA_BASE_ICMS_ST" CHAR(1), OUT "DESCONTA_BASE_PIS_COF" CHAR(1))
BEGIN
    /* Buscar benefícios fiscais associados à natureza */
    FOR SELECT 
        BF.COD_BENEFICIO,
        BF.ID_BENEFICIO,
        BF.NOME_BENEFICIO,
        BF.ICMS_SUBST_TRIB,
        BF.TRATA_ICMS_NORMAL,
        BF.TRATA_PIS_COFINS,
        BF.DESCONTA_BASE_ICMS,
        BF.DESCONTA_BASE_ICMS_ST,
        BF.DESCONTA_BASE_PIS_COF
    FROM 
        BENEFICIO_FISCAL BF
        JOIN NATUREZA_OPER_BENEF_FISCAL NOBF ON BF.COD_BENEFICIO = NOBF.COD_BENEFICIO
    WHERE 
        NOBF.COD_NATUREZA_OPER = :IN_COD_NATUREZA
    INTO 
        :COD_BENEFICIO, :ID_BENEFICIO, :NOME_BENEFICIO, :ICMS_SUBST_TRIB,
        :TRATA_ICMS_NORMAL, :TRATA_PIS_COFINS, :DESCONTA_BASE_ICMS,
        :DESCONTA_BASE_ICMS_ST, :DESCONTA_BASE_PIS_COF
    DO
        SUSPEND;
    
    /* Se não encontrou nenhum benefício, retorna o padrão */
    IF (ROW_COUNT = 0) THEN
    BEGIN
        SELECT 
            COD_BENEFICIO,
            ID_BENEFICIO,
            NOME_BENEFICIO,
            ICMS_SUBST_TRIB,
            TRATA_ICMS_NORMAL,
            TRATA_PIS_COFINS,
            DESCONTA_BASE_ICMS,
            DESCONTA_BASE_ICMS_ST,
            DESCONTA_BASE_PIS_COF
        FROM 
            BENEFICIO_FISCAL
        WHERE 
            COD_BENEFICIO = 0
        INTO 
            :COD_BENEFICIO, :ID_BENEFICIO, :NOME_BENEFICIO, :ICMS_SUBST_TRIB,
            :TRATA_ICMS_NORMAL, :TRATA_PIS_COFINS, :DESCONTA_BASE_ICMS,
            :DESCONTA_BASE_ICMS_ST, :DESCONTA_BASE_PIS_COF;
        
        SUSPEND;
    END
END^
SET TERM ; ^

-- PROCEDURE: SP_NATUREZA_OPERACAO_SIMPLES
SET TERM ^ ;
CREATE PROCEDURE "SP_NATUREZA_OPERACAO_SIMPLES"
(IN "IN_COD_NATUREZA" INTEGER, OUT "COD_NATUREZA_OPER" INTEGER, OUT "NOME_NATUREZA_OPER" VARCHAR(100), OUT "COD_NATUREZA_OPER_CST" INTEGER, OUT "NOME_SUBST_TRIBUTARIA" VARCHAR(100), OUT "NOME_SUBST_TRIBUTARIA_TRAT" VARCHAR(100), OUT "ATV_CONF_TRIBUTACAO" CHAR(1))
BEGIN
    /* Esta procedure usa sintaxe compatível com Firebird 2.5 */
    FOR SELECT 
        N.COD_NATUREZA_OPER,
        N.NOME_NATUREZA_OPER,
        NOC.COD_NATUREZA_OPER_CST,
        ST1.ID_SUBST_TRIBUTARIA || ' - ' || ST1.NOME_SUBST_TRIBUTARIA,
        ST2.ID_SUBST_TRIBUTARIA || ' - ' || ST2.NOME_SUBST_TRIBUTARIA,
        CT.ATV_CONF_TRIBUTACAO
    FROM 
        NATUREZA_OPER N
        LEFT JOIN NATUREZA_OPER_CST NOC ON N.COD_NATUREZA_OPER = NOC.COD_NATUREZA_OPER
        LEFT JOIN SUBST_TRIBUTARIA ST1 ON NOC.COD_SUBST_TRIBUTARIA = ST1.COD_SUBST_TRIBUTARIA
        LEFT JOIN SUBST_TRIBUTARIA ST2 ON NOC.COD_SUBST_TRIBUTARIA_TRATAMENTO = ST2.COD_SUBST_TRIBUTARIA
        LEFT JOIN CONFIGURADOR_TRIBUTACAO CT ON N.COD_NATUREZA_OPER = CT.COD_NATUREZA_OPER
    WHERE 
        N.COD_NATUREZA_OPER = :IN_COD_NATUREZA
    INTO 
        :COD_NATUREZA_OPER, :NOME_NATUREZA_OPER, :COD_NATUREZA_OPER_CST,
        :NOME_SUBST_TRIBUTARIA, :NOME_SUBST_TRIBUTARIA_TRAT, :ATV_CONF_TRIBUTACAO
    DO
        SUSPEND;
END^
SET TERM ; ^

-- PROCEDURE: SP_NATUREZA_OPER_BENEFICIO
SET TERM ^ ;
CREATE PROCEDURE "SP_NATUREZA_OPER_BENEFICIO"
(IN "IN_COD_NATUREZA" INTEGER, OUT "COD_BENEFICIO" INTEGER, OUT "ID_BENEFICIO" VARCHAR(20), OUT "NOME_BENEFICIO" VARCHAR(100), OUT "ICMS_SUBST_TRIB" CHAR(1), OUT "TRATA_ICMS_NORMAL" CHAR(1), OUT "TRATA_PIS_COFINS" CHAR(1), OUT "DESCONTA_BASE_ICMS" CHAR(1), OUT "DESCONTA_BASE_ICMS_ST" CHAR(1), OUT "DESCONTA_BASE_PIS_COF" CHAR(1))
BEGIN
    /* Buscar benefícios fiscais associados à natureza */
    FOR SELECT 
        BF.COD_BENEFICIO,
        BF.ID_BENEFICIO,
        BF.NOME_BENEFICIO,
        BF.ICMS_SUBST_TRIB,
        BF.TRATA_ICMS_NORMAL,
        BF.TRATA_PIS_COFINS,
        BF.DESCONTA_BASE_ICMS,
        BF.DESCONTA_BASE_ICMS_ST,
        BF.DESCONTA_BASE_PIS_COF
    FROM 
        BENEFICIO_FISCAL BF
        JOIN NATUREZA_OPER_BENEF_FISCAL NOBF ON BF.COD_BENEFICIO = NOBF.COD_BENEFICIO
    WHERE 
        NOBF.COD_NATUREZA_OPER = :IN_COD_NATUREZA
    INTO 
        :COD_BENEFICIO, :ID_BENEFICIO, :NOME_BENEFICIO, :ICMS_SUBST_TRIB,
        :TRATA_ICMS_NORMAL, :TRATA_PIS_COFINS, :DESCONTA_BASE_ICMS,
        :DESCONTA_BASE_ICMS_ST, :DESCONTA_BASE_PIS_COF
    DO
        SUSPEND;
    
    /* Se não encontrou nenhum benefício, retorna o padrão */
    IF (ROW_COUNT = 0) THEN
    BEGIN
        SELECT 
            COD_BENEFICIO,
            ID_BENEFICIO,
            NOME_BENEFICIO,
            ICMS_SUBST_TRIB,
            TRATA_ICMS_NORMAL,
            TRATA_PIS_COFINS,
            DESCONTA_BASE_ICMS,
            DESCONTA_BASE_ICMS_ST,
            DESCONTA_BASE_PIS_COF
        FROM 
            BENEFICIO_FISCAL
        WHERE 
            COD_BENEFICIO = 0
        INTO 
            :COD_BENEFICIO, :ID_BENEFICIO, :NOME_BENEFICIO, :ICMS_SUBST_TRIB,
            :TRATA_ICMS_NORMAL, :TRATA_PIS_COFINS, :DESCONTA_BASE_ICMS,
            :DESCONTA_BASE_ICMS_ST, :DESCONTA_BASE_PIS_COF;
        
        SUSPEND;
    END
END^
SET TERM ; ^

-- PROCEDURE: SP_NATUREZA_OPER_BENEF_FISCAL
SET TERM ^ ;
CREATE PROCEDURE "SP_NATUREZA_OPER_BENEF_FISCAL"
(IN "IN_COD_NATUREZA" INTEGER, OUT "COD_BENEFICIO" INTEGER, OUT "ID_BENEFICIO" VARCHAR(20), OUT "NOME_BENEFICIO" VARCHAR(100), OUT "ICMS_SUBST_TRIB" CHAR(1), OUT "TRATA_ICMS_NORMAL" CHAR(1), OUT "TRATA_PIS_COFINS" CHAR(1), OUT "DESCONTA_BASE_ICMS" CHAR(1), OUT "DESCONTA_BASE_ICMS_ST" CHAR(1), OUT "DESCONTA_BASE_PIS_COF" CHAR(1))
BEGIN
    /* Esta é uma procedure alternativa com um nome que pode ser o que a aplicação está procurando */
    FOR SELECT 
        BF.COD_BENEFICIO,
        BF.ID_BENEFICIO,
        BF.NOME_BENEFICIO,
        BF.ICMS_SUBST_TRIB,
        BF.TRATA_ICMS_NORMAL,
        BF.TRATA_PIS_COFINS,
        BF.DESCONTA_BASE_ICMS,
        BF.DESCONTA_BASE_ICMS_ST,
        BF.DESCONTA_BASE_PIS_COF
    FROM 
        BENEFICIO_FISCAL BF
        JOIN NATUREZA_OPER_BENEF_FISCAL NOBF ON BF.COD_BENEFICIO = NOBF.COD_BENEFICIO
    WHERE 
        NOBF.COD_NATUREZA_OPER = :IN_COD_NATUREZA
    INTO 
        :COD_BENEFICIO, :ID_BENEFICIO, :NOME_BENEFICIO, :ICMS_SUBST_TRIB,
        :TRATA_ICMS_NORMAL, :TRATA_PIS_COFINS, :DESCONTA_BASE_ICMS,
        :DESCONTA_BASE_ICMS_ST, :DESCONTA_BASE_PIS_COF
    DO
        SUSPEND;
    
    /* Se não encontrou nenhum benefício, retorna o padrão */
    IF (ROW_COUNT = 0) THEN
    BEGIN
        SELECT 
            COD_BENEFICIO,
            ID_BENEFICIO,
            NOME_BENEFICIO,
            ICMS_SUBST_TRIB,
            TRATA_ICMS_NORMAL,
            TRATA_PIS_COFINS,
            DESCONTA_BASE_ICMS,
            DESCONTA_BASE_ICMS_ST,
            DESCONTA_BASE_PIS_COF
        FROM 
            BENEFICIO_FISCAL
        WHERE 
            COD_BENEFICIO = 0
        INTO 
            :COD_BENEFICIO, :ID_BENEFICIO, :NOME_BENEFICIO, :ICMS_SUBST_TRIB,
            :TRATA_ICMS_NORMAL, :TRATA_PIS_COFINS, :DESCONTA_BASE_ICMS,
            :DESCONTA_BASE_ICMS_ST, :DESCONTA_BASE_PIS_COF;
        
        SUSPEND;
    END
END^
SET TERM ; ^

-- PROCEDURE: SP_NAT_BENEF
SET TERM ^ ;
CREATE PROCEDURE "SP_NAT_BENEF"
(IN "IN_COD_NATUREZA" INTEGER, OUT "COD_NATUREZA_OPER" INTEGER, OUT "COD_BENEFICIO" INTEGER, OUT "ID_BENEFICIO" VARCHAR(20), OUT "NOME_BENEFICIO" VARCHAR(100))
BEGIN
    /* Se o código da natureza for NULL ou 0, retornamos um resultado fictício */
    IF ((IN_COD_NATUREZA IS NULL) OR (IN_COD_NATUREZA = 0)) THEN
    BEGIN
        /* Retornar um registro fictício para evitar o erro */
        SELECT 
            COALESCE(:IN_COD_NATUREZA, 0),
            BF.COD_BENEFICIO,
            BF.ID_BENEFICIO,
            BF.NOME_BENEFICIO
        FROM 
            BENEFICIO_FISCAL BF
        WHERE 
            BF.COD_BENEFICIO = 0
        INTO 
            :COD_NATUREZA_OPER, :COD_BENEFICIO, :ID_BENEFICIO, :NOME_BENEFICIO;
        
        SUSPEND;
        EXIT;
    END
    
    /* Para códigos válidos, proceder normalmente */
    FOR SELECT 
        NOBF.COD_NATUREZA_OPER,
        BF.COD_BENEFICIO,
        BF.ID_BENEFICIO,
        BF.NOME_BENEFICIO
    FROM 
        BENEFICIO_FISCAL BF
        JOIN NATUREZA_OPER_BENEF_FISCAL NOBF ON BF.COD_BENEFICIO = NOBF.COD_BENEFICIO
    WHERE 
        NOBF.COD_NATUREZA_OPER = :IN_COD_NATUREZA
    INTO 
        :COD_NATUREZA_OPER, :COD_BENEFICIO, :ID_BENEFICIO, :NOME_BENEFICIO
    DO
        SUSPEND;
    
    /* Se não encontrou nenhum benefício, retorna o padrão */
    IF (ROW_COUNT = 0) THEN
    BEGIN
        SELECT 
            :IN_COD_NATUREZA,
            BF.COD_BENEFICIO,
            BF.ID_BENEFICIO,
            BF.NOME_BENEFICIO
        FROM 
            BENEFICIO_FISCAL BF
        WHERE 
            BF.COD_BENEFICIO = 0
        INTO 
            :COD_NATUREZA_OPER, :COD_BENEFICIO, :ID_BENEFICIO, :NOME_BENEFICIO;
        
        SUSPEND;
    END
END^
SET TERM ; ^

-- PROCEDURE: SP_SINCRONIZAR_BENEFICIOS
SET TERM ^ ;
CREATE PROCEDURE "SP_SINCRONIZAR_BENEFICIOS"
(OUT "REGISTROS_CRIADOS" INTEGER)
DECLARE VARIABLE V_COD_NATUREZA INTEGER;
DECLARE VARIABLE V_COD_SUBST_TRIBUTARIA INTEGER;
DECLARE VARIABLE V_CBENEF VARCHAR(10);
DECLARE VARIABLE V_COD_BENEFICIO INTEGER;
BEGIN
    REGISTROS_CRIADOS = 0;
    
    /* Converter dados de NATUREZA_BENEFICIO_FISCAL para a nova estrutura */
    FOR SELECT 
            NBF.COD_NATUREZA_OPER,
            NBF.COD_SUBST_TRIBUTARIA,
            NBF.CBENEF
        FROM 
            NATUREZA_BENEFICIO_FISCAL NBF
        INTO 
            :V_COD_NATUREZA, :V_COD_SUBST_TRIBUTARIA, :V_CBENEF
    DO
    BEGIN
        /* Verificar se já existe um benefício com esse CBENEF */
        SELECT FIRST 1 
            BF.COD_BENEFICIO 
        FROM 
            BENEFICIO_FISCAL BF 
        WHERE 
            BF.ID_BENEFICIO = :V_CBENEF
        INTO 
            :V_COD_BENEFICIO;
        
        /* Se não existe, criar */
        IF (V_COD_BENEFICIO IS NULL) THEN
        BEGIN
            /* Obter informações da SUBST_TRIBUTARIA */
            INSERT INTO BENEFICIO_FISCAL (
                ID_BENEFICIO, 
                NOME_BENEFICIO, 
                ICMS_SUBST_TRIB
            )
            SELECT 
                :V_CBENEF,
                COALESCE(ST.NOME_SUBST_TRIBUTARIA, 'Benefício ' || :V_CBENEF),
                'S'
            FROM 
                SUBST_TRIBUTARIA ST
            WHERE 
                ST.COD_SUBST_TRIBUTARIA = :V_COD_SUBST_TRIBUTARIA;
            
            /* Obter o ID gerado */
            V_COD_BENEFICIO = GEN_ID(SEQ_BENEFICIO_FISCAL, 0);
        END
        
        /* Associar à natureza se ainda não estiver associado */
        IF (NOT EXISTS(
            SELECT 1 FROM NATUREZA_OPER_BENEF_FISCAL 
            WHERE COD_NATUREZA_OPER = :V_COD_NATUREZA 
            AND COD_BENEFICIO = :V_COD_BENEFICIO
        )) THEN
        BEGIN
            INSERT INTO NATUREZA_OPER_BENEF_FISCAL (
                COD_NATUREZA_OPER, 
                COD_BENEFICIO
            ) VALUES (
                :V_COD_NATUREZA, 
                :V_COD_BENEFICIO
            );
            
            REGISTROS_CRIADOS = REGISTROS_CRIADOS + 1;
        END
    END
    
    /* Associar o benefício padrão para naturezas sem benefício */
    FOR SELECT 
            N.COD_NATUREZA_OPER
        FROM 
            NATUREZA_OPER N
        WHERE 
            NOT EXISTS (
                SELECT 1 FROM NATUREZA_OPER_BENEF_FISCAL 
                WHERE COD_NATUREZA_OPER = N.COD_NATUREZA_OPER
            )
        INTO 
            :V_COD_NATUREZA
    DO
    BEGIN
        INSERT INTO NATUREZA_OPER_BENEF_FISCAL (
            COD_NATUREZA_OPER, 
            COD_BENEFICIO
        ) VALUES (
            :V_COD_NATUREZA, 
            0
        );
        
        REGISTROS_CRIADOS = REGISTROS_CRIADOS + 1;
    END
    
    SUSPEND;
END^
SET TERM ; ^

-- PROCEDURE: SP_SINC_BENEFICIOS
SET TERM ^ ;
CREATE PROCEDURE "SP_SINC_BENEFICIOS"
(OUT "REGISTROS_CRIADOS" INTEGER)
DECLARE VARIABLE V_COD_NATUREZA INTEGER;
DECLARE VARIABLE V_COD_SUBST_TRIBUTARIA INTEGER;
DECLARE VARIABLE V_CBENEF VARCHAR(10);
DECLARE VARIABLE V_COD_BENEFICIO INTEGER;
BEGIN
    REGISTROS_CRIADOS = 0;
    
    /* Converter dados de NATUREZA_BENEFICIO_FISCAL para a nova estrutura */
    FOR SELECT 
            NBF.COD_NATUREZA_OPER,
            NBF.COD_SUBST_TRIBUTARIA,
            NBF.CBENEF
        FROM 
            NATUREZA_BENEFICIO_FISCAL NBF
        INTO 
            :V_COD_NATUREZA, :V_COD_SUBST_TRIBUTARIA, :V_CBENEF
    DO
    BEGIN
        /* Verificar se já existe um benefício com esse CBENEF */
        SELECT FIRST 1 
            BF.COD_BENEFICIO 
        FROM 
            BENEFICIO_FISCAL BF 
        WHERE 
            BF.ID_BENEFICIO = :V_CBENEF
        INTO 
            :V_COD_BENEFICIO;
        
        /* Se não existe, criar */
        IF (V_COD_BENEFICIO IS NULL) THEN
        BEGIN
            /* Obter informações da SUBST_TRIBUTARIA */
            INSERT INTO BENEFICIO_FISCAL (
                ID_BENEFICIO, 
                NOME_BENEFICIO, 
                ICMS_SUBST_TRIB
            )
            SELECT 
                :V_CBENEF,
                COALESCE(ST.NOME_SUBST_TRIBUTARIA, 'Benefício ' || :V_CBENEF),
                'S'
            FROM 
                SUBST_TRIBUTARIA ST
            WHERE 
                ST.COD_SUBST_TRIBUTARIA = :V_COD_SUBST_TRIBUTARIA;
            
            /* Obter o ID gerado */
            V_COD_BENEFICIO = GEN_ID(SEQ_BENEFICIO_FISCAL, 0);
        END
        
        /* Associar à natureza se ainda não estiver associado */
        IF (NOT EXISTS(
            SELECT 1 FROM NATUREZA_OPER_BENEF_FISCAL 
            WHERE COD_NATUREZA_OPER = :V_COD_NATUREZA 
            AND COD_BENEFICIO = :V_COD_BENEFICIO
        )) THEN
        BEGIN
            INSERT INTO NATUREZA_OPER_BENEF_FISCAL (
                COD_NATUREZA_OPER, 
                COD_BENEFICIO
            ) VALUES (
                :V_COD_NATUREZA, 
                :V_COD_BENEFICIO
            );
            
            REGISTROS_CRIADOS = REGISTROS_CRIADOS + 1;
        END
    END
    
    /* Associar o benefício padrão para naturezas sem benefício */
    FOR SELECT 
            N.COD_NATUREZA_OPER
        FROM 
            NATUREZA_OPER N
        WHERE 
            NOT EXISTS (
                SELECT 1 FROM NATUREZA_OPER_BENEF_FISCAL 
                WHERE COD_NATUREZA_OPER = N.COD_NATUREZA_OPER
            )
        INTO 
            :V_COD_NATUREZA
    DO
    BEGIN
        INSERT INTO NATUREZA_OPER_BENEF_FISCAL (
            COD_NATUREZA_OPER, 
            COD_BENEFICIO
        ) VALUES (
            :V_COD_NATUREZA, 
            0
        );
        
        REGISTROS_CRIADOS = REGISTROS_CRIADOS + 1;
    END
    
    SUSPEND;
END^
SET TERM ; ^

-- PROCEDURE: SP_TESTAR
SET TERM ^ ;
CREATE PROCEDURE "SP_TESTAR"
(OUT "MENSAGEM" VARCHAR(100))
BEGIN
    /* Verificar benefício fiscal padrão */
    IF (EXISTS(SELECT 1 FROM BENEFICIO_FISCAL WHERE COD_BENEFICIO = 0)) THEN
    BEGIN
        MENSAGEM = 'Benefício fiscal padrão OK';
        SUSPEND;
    END
    ELSE
    BEGIN
        MENSAGEM = 'ERRO: Benefício fiscal padrão não encontrado';
        SUSPEND;
        EXIT;
    END
    
    /* Verificar tabela de relacionamento */
    IF (EXISTS(SELECT 1 FROM NATUREZA_OPER_BENEF_FISCAL)) THEN
    BEGIN
        MENSAGEM = 'Tabela de relacionamento possui dados';
        SUSPEND;
    END
    ELSE
    BEGIN
        MENSAGEM = 'Tabela de relacionamento vazia - execute SP_ASSOCIAR_BENEFICIO_PADRAO';
        SUSPEND;
    END
    
    /* Verificar procedure principal */
    IF (EXISTS(SELECT FIRST 1 1 FROM SP_NATUREZA_BENEFICIO(0))) THEN
    BEGIN
        MENSAGEM = 'Procedure principal funcionando';
        SUSPEND;
    END
    ELSE
    BEGIN
        MENSAGEM = 'ERRO: Procedure principal não retornou dados';
        SUSPEND;
    END
END^
SET TERM ; ^

-- PROCEDURE: SP_TESTE_BENEFICIO
SET TERM ^ ;
CREATE PROCEDURE "SP_TESTE_BENEFICIO"
(OUT "MENSAGEM" VARCHAR(200), OUT "STATUS" INTEGER)
BEGIN
    MENSAGEM = 'Verificando tabela BENEFICIO_FISCAL';
    STATUS = 1;
    SUSPEND;
    
    IF (NOT EXISTS(SELECT 1 FROM BENEFICIO_FISCAL WHERE COD_BENEFICIO = 0)) THEN
    BEGIN
        MENSAGEM = 'Erro: Benefício fiscal padrão não encontrado';
        STATUS = 0;
        SUSPEND;
        EXIT;
    END
    
    MENSAGEM = 'Verificando tabela NATUREZA_OPER_BENEF_FISCAL';
    STATUS = 1;
    SUSPEND;
    
    IF (NOT EXISTS(SELECT 1 FROM NATUREZA_OPER_BENEF_FISCAL)) THEN
    BEGIN
        MENSAGEM = 'Erro: Nenhuma associação encontrada';
        STATUS = 0;
        SUSPEND;
        EXIT;
    END
    
    MENSAGEM = 'Testando procedure SP_NATUREZA_BENEFICIO';
    STATUS = 1;
    SUSPEND;
    
    IF (NOT EXISTS(SELECT FIRST 1 1 FROM SP_NATUREZA_BENEFICIO(0))) THEN
    BEGIN
        MENSAGEM = 'Erro: Procedure não retornou resultados';
        STATUS = 0;
        SUSPEND;
        EXIT;
    END
    
    MENSAGEM = 'Teste concluído com sucesso';
    STATUS = 1;
    SUSPEND;
END^
SET TERM ; ^

-- PROCEDURE: SP_TESTE_INTEGRACAO_BENEFICIO
SET TERM ^ ;
CREATE PROCEDURE "SP_TESTE_INTEGRACAO_BENEFICIO"
(OUT "MENSAGEM" VARCHAR(200), OUT "STATUS" INTEGER)
BEGIN
    MENSAGEM = 'Verificando tabela BENEFICIO_FISCAL';
    STATUS = 1;
    SUSPEND;
    
    IF (NOT EXISTS(SELECT 1 FROM BENEFICIO_FISCAL WHERE COD_BENEFICIO = 0)) THEN
    BEGIN
        MENSAGEM = 'Erro: Benefício fiscal padrão não encontrado';
        STATUS = 0;
        SUSPEND;
        EXIT;
    END
    
    MENSAGEM = 'Verificando tabela NATUREZA_OPER_BENEF_FISCAL';
    STATUS = 1;
    SUSPEND;
    
    IF (NOT EXISTS(SELECT 1 FROM NATUREZA_OPER_BENEF_FISCAL)) THEN
    BEGIN
        MENSAGEM = 'Erro: Nenhuma associação de natureza com benefício encontrada';
        STATUS = 0;
        SUSPEND;
        EXIT;
    END
    
    MENSAGEM = 'Testando procedure SP_NATUREZA_OPER_BENEFICIO';
    STATUS = 1;
    SUSPEND;
    
    IF (NOT EXISTS(SELECT FIRST 1 1 FROM SP_NATUREZA_OPER_BENEFICIO(0))) THEN
    BEGIN
        MENSAGEM = 'Erro: Procedure SP_NATUREZA_OPER_BENEFICIO não retornou resultados';
        STATUS = 0;
        SUSPEND;
        EXIT;
    END
    
    MENSAGEM = 'Teste de integração concluído com sucesso';
    STATUS = 1;
    SUSPEND;
END^
SET TERM ; ^

-- PROCEDURE: SP_TESTE_NATUREZA
SET TERM ^ ;
CREATE PROCEDURE "SP_TESTE_NATUREZA"
(IN "IN_COD_NATUREZA" INTEGER, OUT "COD_NATUREZA_OPER" INTEGER, OUT "NOME_NATUREZA_OPER" VARCHAR(100))
BEGIN
  SELECT COD_NATUREZA_OPER, NOME_NATUREZA_OPER
  FROM NATUREZA_OPER
  WHERE COD_NATUREZA_OPER = :IN_COD_NATUREZA
  INTO :COD_NATUREZA_OPER, :NOME_NATUREZA_OPER;
  
  SUSPEND;
END^
SET TERM ; ^

-- PROCEDURE: SP_VALIDA_NATUREZA
SET TERM ^ ;
CREATE PROCEDURE "SP_VALIDA_NATUREZA"
(IN "IN_COD_NATUREZA" INTEGER, OUT "NATUREZA_VALIDA" INTEGER)
DECLARE VARIABLE V_COUNT INTEGER;
BEGIN
    SELECT COUNT(*) FROM NATUREZA_OPER 
    WHERE COD_NATUREZA_OPER = :IN_COD_NATUREZA
    INTO :V_COUNT;
    
    IF (V_COUNT = 0) THEN
        EXCEPTION ERRO_NATUREZA_INVALIDA;
    ELSE
        NATUREZA_VALIDA = 1;
        
    SUSPEND;
END^
SET TERM ; ^

-- PROCEDURE: SP_VERIFICA_ESTRUTURA
SET TERM ^ ;
CREATE PROCEDURE "SP_VERIFICA_ESTRUTURA"
(OUT "TABELA" VARCHAR(50), OUT "EXISTE" VARCHAR(3))
BEGIN
    TABELA = 'BENEFICIO_FISCAL';
    IF (EXISTS(SELECT 1 FROM RDB$RELATIONS WHERE RDB$RELATION_NAME = 'BENEFICIO_FISCAL')) THEN
        EXISTE = 'SIM';
    ELSE
        EXISTE = 'NÃO';
    SUSPEND;
    
    TABELA = 'NATUREZA_OPER_BENEF_FISCAL';
    IF (EXISTS(SELECT 1 FROM RDB$RELATIONS WHERE RDB$RELATION_NAME = 'NATUREZA_OPER_BENEF_FISCAL')) THEN
        EXISTE = 'SIM';
    ELSE
        EXISTE = 'NÃO';
    SUSPEND;
END^
SET TERM ; ^


-- ============================================================
-- GENERATOR/SEQUENCE: faltando em PROCEL e existentes em BASE_CONFIGURADA
-- ============================================================

-- GENERATOR/SEQUENCE: GEN_IBESCRIPTS_ID
CREATE SEQUENCE "GEN_IBESCRIPTS_ID";

-- GENERATOR/SEQUENCE: GEN_MONITOR_QUERIES_ID
CREATE SEQUENCE "GEN_MONITOR_QUERIES_ID";

-- GENERATOR/SEQUENCE: SEQ_BENEFICIO_FISCAL
CREATE SEQUENCE "SEQ_BENEFICIO_FISCAL";

-- GENERATOR/SEQUENCE: SEQ_CONTA_FINANCEIRA_10
CREATE SEQUENCE "SEQ_CONTA_FINANCEIRA_10";

-- GENERATOR/SEQUENCE: SEQ_CONTA_FINANCEIRA_12
CREATE SEQUENCE "SEQ_CONTA_FINANCEIRA_12";

-- GENERATOR/SEQUENCE: SEQ_CONTA_FINANCEIRA_13
CREATE SEQUENCE "SEQ_CONTA_FINANCEIRA_13";

-- GENERATOR/SEQUENCE: SEQ_CONTA_FINANCEIRA_14
CREATE SEQUENCE "SEQ_CONTA_FINANCEIRA_14";

-- GENERATOR/SEQUENCE: SEQ_CONTA_FINANCEIRA_18
CREATE SEQUENCE "SEQ_CONTA_FINANCEIRA_18";

-- GENERATOR/SEQUENCE: SEQ_CONTA_FINANCEIRA_19
CREATE SEQUENCE "SEQ_CONTA_FINANCEIRA_19";

-- GENERATOR/SEQUENCE: SEQ_CONTA_FINANCEIRA_20
CREATE SEQUENCE "SEQ_CONTA_FINANCEIRA_20";

-- GENERATOR/SEQUENCE: SEQ_CONTA_FINANCEIRA_21
CREATE SEQUENCE "SEQ_CONTA_FINANCEIRA_21";

-- GENERATOR/SEQUENCE: SEQ_CONTA_FINANCEIRA_23
CREATE SEQUENCE "SEQ_CONTA_FINANCEIRA_23";

-- GENERATOR/SEQUENCE: SEQ_CONTA_FINANCEIRA_27
CREATE SEQUENCE "SEQ_CONTA_FINANCEIRA_27";

-- GENERATOR/SEQUENCE: SEQ_CONTA_FINANCEIRA_30
CREATE SEQUENCE "SEQ_CONTA_FINANCEIRA_30";

-- GENERATOR/SEQUENCE: SEQ_CONTA_FINANCEIRA_8
CREATE SEQUENCE "SEQ_CONTA_FINANCEIRA_8";

-- GENERATOR/SEQUENCE: SEQ_CONTA_FINANCEIRA_9
CREATE SEQUENCE "SEQ_CONTA_FINANCEIRA_9";

-- GENERATOR/SEQUENCE: SEQ_DAV_EMP_1
CREATE SEQUENCE "SEQ_DAV_EMP_1";

-- GENERATOR/SEQUENCE: SEQ_NN_CF_7
CREATE SEQUENCE "SEQ_NN_CF_7";


-- ============================================================
-- TRIGGER: faltando em PROCEL e existentes em BASE_CONFIGURADA
-- ============================================================

-- TRIGGER: CALCULAR_ANTIGUIDADE_FORNECEDOR
SET TERM ^ ;
CREATE TRIGGER "CALCULAR_ANTIGUIDADE_FORNECEDOR" FOR "GERFORNECEDOR"
ACTIVE BEFORE INSERT OR UPDATE POSITION 0
AS
BEGIN
    IF (NEW.DATA_NASC_FORNECEDOR IS NOT NULL) THEN
    BEGIN
        -- Calcula o total de anos de fundação
        NEW.CODIGO_ANTIGO = EXTRACT(YEAR FROM CURRENT_DATE) - EXTRACT(YEAR FROM NEW.DATA_NASC_FORNECEDOR);
        
        -- Caso o mês ou dia da fundação ainda não tenha ocorrido neste ano, subtrai 1
        IF (EXTRACT(MONTH FROM CURRENT_DATE) < EXTRACT(MONTH FROM NEW.DATA_NASC_FORNECEDOR)) THEN
        BEGIN
            NEW.CODIGO_ANTIGO = NEW.CODIGO_ANTIGO - 1;
        END
        ELSE IF (EXTRACT(MONTH FROM CURRENT_DATE) = EXTRACT(MONTH FROM NEW.DATA_NASC_FORNECEDOR) AND EXTRACT(DAY FROM CURRENT_DATE) < EXTRACT(DAY FROM NEW.DATA_NASC_FORNECEDOR)) THEN
        BEGIN
            NEW.CODIGO_ANTIGO = NEW.CODIGO_ANTIGO - 1;
        END
    END
END^
SET TERM ; ^

-- TRIGGER: CALCULAR_IDADE_BI
SET TERM ^ ;
CREATE TRIGGER "CALCULAR_IDADE_BI" FOR "VTCENTRO_CUSTO"
ACTIVE BEFORE INSERT OR UPDATE POSITION 0
AS
BEGIN
    IF (NEW.DATA_NASCIMENTO IS NOT NULL) THEN
    BEGIN
        NEW.IDADE = EXTRACT(YEAR FROM CURRENT_DATE) - EXTRACT(YEAR FROM NEW.DATA_NASCIMENTO);
    END
END^
SET TERM ; ^

-- TRIGGER: CHECK_COD_FORNECEDOR
SET TERM ^ ;
CREATE TRIGGER "CHECK_COD_FORNECEDOR" FOR "FORNECEDOR_PRODUTO"
ACTIVE BEFORE INSERT POSITION 0
AS
DECLARE VARIABLE tmp_exists INTEGER;
BEGIN
  SELECT COUNT(*)
  FROM GERFORNECEDOR
  WHERE COD_FORNECEDOR = NEW.COD_FORNECEDOR
  INTO :tmp_exists;

  IF (tmp_exists = 0) THEN
  BEGIN
    INSERT INTO GERFORNECEDOR (COD_FORNECEDOR, NOME_FORNECEDOR, COD_TIPO_FORNECEDOR, RAZAO_SOCIAL_FORNECEDOR)
    VALUES (0, 'Temporário', 1, 'Temporário');
  END
END^
SET TERM ; ^

-- TRIGGER: LISTA_PRESENTES_TS
SET TERM ^ ;
CREATE TRIGGER "LISTA_PRESENTES_TS" FOR "LISTA_PRESENTES"
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  if ((new.COD_LISTA_PRESENTES IS null) OR (new.COD_LISTA_PRESENTES<0)) then
    new.COD_LISTA_PRESENTES = gen_id(SEQ_LISTA_PRESENTES,1);
END^
SET TERM ; ^

-- TRIGGER: LISTA_PRESENTE_ITEM_TS
SET TERM ^ ;
CREATE TRIGGER "LISTA_PRESENTE_ITEM_TS" FOR "LISTA_PRESENTE_ITEM"
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  if ((new.COD_LISTA_PRESENTE_ITEM IS null) OR (new.COD_LISTA_PRESENTE_ITEM<=0)) then
    new.COD_LISTA_PRESENTE_ITEM = gen_id(SEQ_LISTA_PRESENTE_ITEM,1);
END^
SET TERM ; ^

-- TRIGGER: MONITOR_QUERIES_BI
SET TERM ^ ;
CREATE TRIGGER "MONITOR_QUERIES_BI" FOR "MONITOR_QUERIES"
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.QUERY_ID IS NULL) THEN
    NEW.QUERY_ID = GEN_ID(GEN_MONITOR_QUERIES_ID,1);
END^
SET TERM ; ^

-- TRIGGER: TELEFONE_CLIENTE_CLI_DTAC
SET TERM ^ ;
CREATE TRIGGER "TELEFONE_CLIENTE_CLI_DTAC" FOR "TELEFONE_CLIENTE"
ACTIVE AFTER INSERT OR UPDATE OR DELETE POSITION 10
AS
BEGIN
  IF ((INSERTING) OR (UPDATING)) THEN
    UPDATE VTCENTRO_CUSTO SET DTAC_VTCENTRO_CUSTO = CURRENT_TIMESTAMP WHERE COD_CC = NEW.COD_CC;
  ELSE
    UPDATE VTCENTRO_CUSTO SET DTAC_VTCENTRO_CUSTO = CURRENT_TIMESTAMP WHERE COD_CC = OLD.COD_CC;
END^
SET TERM ; ^

-- TRIGGER: TIPO_TELEFONE_DTAC
SET TERM ^ ;
CREATE TRIGGER "TIPO_TELEFONE_DTAC" FOR "TIPO_TELEFONE"
ACTIVE BEFORE UPDATE POSITION 10
AS
BEGIN
    new.DTAC_TIPO_TELEFONE = current_timestamp;
END^
SET TERM ; ^

-- TRIGGER: TRG_BENEFICIO_FISCAL_BI
SET TERM ^ ;
CREATE TRIGGER "TRG_BENEFICIO_FISCAL_BI" FOR "BENEFICIO_FISCAL"
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
    IF ((NEW.COD_BENEFICIO IS NULL) OR (NEW.COD_BENEFICIO <= 0)) THEN
        NEW.COD_BENEFICIO = GEN_ID(SEQ_BENEFICIO_FISCAL, 1);
END^
SET TERM ; ^

-- TRIGGER: TRG_NATUREZA_OPER_AI
SET TERM ^ ;
CREATE TRIGGER "TRG_NATUREZA_OPER_AI" FOR "NATUREZA_OPER"
ACTIVE AFTER INSERT POSITION 0
AS
BEGIN
    /* Associar automaticamente o benefício padrão para novas naturezas */
    IF (NOT EXISTS(
        SELECT 1 FROM NATUREZA_OPER_BENEF_FISCAL 
        WHERE COD_NATUREZA_OPER = NEW.COD_NATUREZA_OPER
    )) THEN
        INSERT INTO NATUREZA_OPER_BENEF_FISCAL (COD_NATUREZA_OPER, COD_BENEFICIO)
        VALUES (NEW.COD_NATUREZA_OPER, 0);
END^
SET TERM ; ^

-- TRIGGER: TRG_NATUREZA_OPER_BENEF_BI
SET TERM ^ ;
CREATE TRIGGER "TRG_NATUREZA_OPER_BENEF_BI" FOR "NATUREZA_OPER"
ACTIVE AFTER INSERT POSITION 0
AS
BEGIN
    /* Associar automaticamente o benefício padrão para novas naturezas */
    IF (NOT EXISTS(
        SELECT 1 FROM NATUREZA_OPER_BENEF_FISCAL 
        WHERE COD_NATUREZA_OPER = NEW.COD_NATUREZA_OPER
    )) THEN
        INSERT INTO NATUREZA_OPER_BENEF_FISCAL (COD_NATUREZA_OPER, COD_BENEFICIO)
        VALUES (NEW.COD_NATUREZA_OPER, 0);
END^
SET TERM ; ^

-- TRIGGER: TRG_NATUREZA_OPER_BI
SET TERM ^ ;
CREATE TRIGGER "TRG_NATUREZA_OPER_BI" FOR "NATUREZA_OPER"
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
    /* Se o código da natureza for NULL ou 0, inserimos um registro temporário na tabela de benefícios */
    IF ((NEW.COD_NATUREZA_OPER IS NULL) OR (NEW.COD_NATUREZA_OPER = 0)) THEN
    BEGIN
        /* O código real será gerado pelo trigger NATUREZA_OPER_TS existente */
        /* Nada a fazer aqui, só evitar o erro */
    END
END^
SET TERM ; ^

-- TRIGGER: TRG_NATUREZA_OPER_CST_BI
SET TERM ^ ;
CREATE TRIGGER "TRG_NATUREZA_OPER_CST_BI" FOR "NATUREZA_OPER_CST"
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.COD_NATUREZA_OPER IS NULL) THEN
    NEW.COD_NATUREZA_OPER = 0;
END^
SET TERM ; ^

-- TRIGGER: TRG_NAT_BENEF_BI
SET TERM ^ ;
CREATE TRIGGER "TRG_NAT_BENEF_BI" FOR "NATUREZA_OPER"
ACTIVE AFTER INSERT POSITION 0
AS
BEGIN
    /* Associar automaticamente o benefício padrão para novas naturezas */
    IF (NOT EXISTS(
        SELECT 1 FROM NATUREZA_OPER_BENEF_FISCAL 
        WHERE COD_NATUREZA_OPER = NEW.COD_NATUREZA_OPER
    )) THEN
        INSERT INTO NATUREZA_OPER_BENEF_FISCAL (COD_NATUREZA_OPER, COD_BENEFICIO)
        VALUES (NEW.COD_NATUREZA_OPER, 0);
END^
SET TERM ; ^

-- TRIGGER: TRG_NAT_BI
SET TERM ^ ;
CREATE TRIGGER "TRG_NAT_BI" FOR "NATUREZA_OPER"
ACTIVE AFTER INSERT POSITION 0
AS
BEGIN
    /* Associar automaticamente o benefício padrão para novas naturezas */
    IF (NOT EXISTS(
        SELECT 1 FROM NATUREZA_OPER_BENEF_FISCAL 
        WHERE COD_NATUREZA_OPER = NEW.COD_NATUREZA_OPER
    )) THEN
        INSERT INTO NATUREZA_OPER_BENEF_FISCAL (COD_NATUREZA_OPER, COD_BENEFICIO)
        VALUES (NEW.COD_NATUREZA_OPER, 0);
END^
SET TERM ; ^

-- TRIGGER: UPDATE_COD_FORNECEDOR
SET TERM ^ ;
CREATE TRIGGER "UPDATE_COD_FORNECEDOR" FOR "GERFORNECEDOR"
ACTIVE AFTER UPDATE OR DELETE POSITION 0
AS
DECLARE VARIABLE tmp_exists INTEGER;
BEGIN
  SELECT COUNT(*)
  FROM GERFORNECEDOR
  WHERE COD_FORNECEDOR = 0
  INTO :tmp_exists;

  IF (tmp_exists > 0) THEN
  BEGIN
    UPDATE FORNECEDOR_PRODUTO
    SET COD_FORNECEDOR = NEW.COD_FORNECEDOR
    WHERE COD_FORNECEDOR = 0;

    DELETE FROM GERFORNECEDOR
    WHERE COD_FORNECEDOR = 0;
  END
END^
SET TERM ; ^

-- TRIGGER: VTCENTRO_CUSTO_DTD
SET TERM ^ ;
CREATE TRIGGER "VTCENTRO_CUSTO_DTD" FOR "VTCENTRO_CUSTO"
ACTIVE BEFORE UPDATE OR DELETE POSITION 9
AS
BEGIN
  IF (UPDATING) THEN
  BEGIN
    IF ((COALESCE(OLD.ATV_VTCENTRO_CUSTO, '') = 'V') AND (COALESCE(NEW.ATV_VTCENTRO_CUSTO, '') = 'F')) THEN
      INSERT INTO CARGA_INATIVADOS (TABELA, PK) VALUES ('VTCENTRO_CUSTO', NEW.COD_CC);
  END
  IF (DELETING) THEN
    INSERT INTO CARGA_INATIVADOS (TABELA, PK) VALUES ('VTCENTRO_CUSTO', OLD.COD_CC);
END^
SET TERM ; ^
